// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.7
//   protoc               unknown
// source: byx/payments/v1/query.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { PageRequest, PageResponse } from "../../../cosmos/base/query/v1beta1/pagination";
import { Params } from "./params";
import { PaymentRequest } from "./payment";

export const protobufPackage = "byx.payments.v1";

/** QueryParamsRequest is request type for the Query/Params RPC method. */
export interface QueryParamsRequest {
}

/** QueryParamsResponse is response type for the Query/Params RPC method. */
export interface QueryParamsResponse {
  /** params holds all the parameters of this module. */
  params: Params | undefined;
}

export interface QueryGetPaymentRequestRequest {
  id: number;
}

export interface QueryGetPaymentRequestResponse {
  paymentRequest: PaymentRequest | undefined;
}

export interface QueryPaymentRequestsByLojaRequest {
  lojaId: number;
  pagination: PageRequest | undefined;
}

export interface QueryPaymentRequestsByLojaResponse {
  paymentRequests: PaymentRequest[];
  pagination: PageResponse | undefined;
}

export interface QueryPaymentsQRCodeRequest {
  requestId: number;
  suggestedCertificateId: number;
}

export interface QueryPaymentsQRCodeResponse {
  requestId: string;
  amountUbyx: number;
  merchantId: number;
  merchantOwner: string;
  suggestedCertificateId: number;
  /** JSON compacto pronto para virar QR: {"t":"byxpay","rid":"...","amt":"...","mid":1,"to":"byx1..."} */
  qrPayload: string;
}

function createBaseQueryParamsRequest(): QueryParamsRequest {
  return {};
}

export const QueryParamsRequest: MessageFns<QueryParamsRequest> = {
  encode(_: QueryParamsRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryParamsRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryParamsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): QueryParamsRequest {
    return {};
  },

  toJSON(_: QueryParamsRequest): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryParamsRequest>, I>>(base?: I): QueryParamsRequest {
    return QueryParamsRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryParamsRequest>, I>>(_: I): QueryParamsRequest {
    const message = createBaseQueryParamsRequest();
    return message;
  },
};

function createBaseQueryParamsResponse(): QueryParamsResponse {
  return { params: undefined };
}

export const QueryParamsResponse: MessageFns<QueryParamsResponse> = {
  encode(message: QueryParamsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.params !== undefined) {
      Params.encode(message.params, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryParamsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryParamsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.params = Params.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryParamsResponse {
    return { params: isSet(object.params) ? Params.fromJSON(object.params) : undefined };
  },

  toJSON(message: QueryParamsResponse): unknown {
    const obj: any = {};
    if (message.params !== undefined) {
      obj.params = Params.toJSON(message.params);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryParamsResponse>, I>>(base?: I): QueryParamsResponse {
    return QueryParamsResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryParamsResponse>, I>>(object: I): QueryParamsResponse {
    const message = createBaseQueryParamsResponse();
    message.params = (object.params !== undefined && object.params !== null)
      ? Params.fromPartial(object.params)
      : undefined;
    return message;
  },
};

function createBaseQueryGetPaymentRequestRequest(): QueryGetPaymentRequestRequest {
  return { id: 0 };
}

export const QueryGetPaymentRequestRequest: MessageFns<QueryGetPaymentRequestRequest> = {
  encode(message: QueryGetPaymentRequestRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).uint64(message.id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryGetPaymentRequestRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryGetPaymentRequestRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = longToNumber(reader.uint64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryGetPaymentRequestRequest {
    return { id: isSet(object.id) ? globalThis.Number(object.id) : 0 };
  },

  toJSON(message: QueryGetPaymentRequestRequest): unknown {
    const obj: any = {};
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryGetPaymentRequestRequest>, I>>(base?: I): QueryGetPaymentRequestRequest {
    return QueryGetPaymentRequestRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryGetPaymentRequestRequest>, I>>(
    object: I,
  ): QueryGetPaymentRequestRequest {
    const message = createBaseQueryGetPaymentRequestRequest();
    message.id = object.id ?? 0;
    return message;
  },
};

function createBaseQueryGetPaymentRequestResponse(): QueryGetPaymentRequestResponse {
  return { paymentRequest: undefined };
}

export const QueryGetPaymentRequestResponse: MessageFns<QueryGetPaymentRequestResponse> = {
  encode(message: QueryGetPaymentRequestResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.paymentRequest !== undefined) {
      PaymentRequest.encode(message.paymentRequest, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryGetPaymentRequestResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryGetPaymentRequestResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.paymentRequest = PaymentRequest.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryGetPaymentRequestResponse {
    return {
      paymentRequest: isSet(object.paymentRequest)
        ? PaymentRequest.fromJSON(object.paymentRequest)
        : isSet(object.payment_request)
        ? PaymentRequest.fromJSON(object.payment_request)
        : undefined,
    };
  },

  toJSON(message: QueryGetPaymentRequestResponse): unknown {
    const obj: any = {};
    if (message.paymentRequest !== undefined) {
      obj.paymentRequest = PaymentRequest.toJSON(message.paymentRequest);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryGetPaymentRequestResponse>, I>>(base?: I): QueryGetPaymentRequestResponse {
    return QueryGetPaymentRequestResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryGetPaymentRequestResponse>, I>>(
    object: I,
  ): QueryGetPaymentRequestResponse {
    const message = createBaseQueryGetPaymentRequestResponse();
    message.paymentRequest = (object.paymentRequest !== undefined && object.paymentRequest !== null)
      ? PaymentRequest.fromPartial(object.paymentRequest)
      : undefined;
    return message;
  },
};

function createBaseQueryPaymentRequestsByLojaRequest(): QueryPaymentRequestsByLojaRequest {
  return { lojaId: 0, pagination: undefined };
}

export const QueryPaymentRequestsByLojaRequest: MessageFns<QueryPaymentRequestsByLojaRequest> = {
  encode(message: QueryPaymentRequestsByLojaRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.lojaId !== 0) {
      writer.uint32(8).uint64(message.lojaId);
    }
    if (message.pagination !== undefined) {
      PageRequest.encode(message.pagination, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryPaymentRequestsByLojaRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryPaymentRequestsByLojaRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.lojaId = longToNumber(reader.uint64());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.pagination = PageRequest.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryPaymentRequestsByLojaRequest {
    return {
      lojaId: isSet(object.lojaId)
        ? globalThis.Number(object.lojaId)
        : isSet(object.loja_id)
        ? globalThis.Number(object.loja_id)
        : 0,
      pagination: isSet(object.pagination) ? PageRequest.fromJSON(object.pagination) : undefined,
    };
  },

  toJSON(message: QueryPaymentRequestsByLojaRequest): unknown {
    const obj: any = {};
    if (message.lojaId !== 0) {
      obj.lojaId = Math.round(message.lojaId);
    }
    if (message.pagination !== undefined) {
      obj.pagination = PageRequest.toJSON(message.pagination);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryPaymentRequestsByLojaRequest>, I>>(
    base?: I,
  ): QueryPaymentRequestsByLojaRequest {
    return QueryPaymentRequestsByLojaRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryPaymentRequestsByLojaRequest>, I>>(
    object: I,
  ): QueryPaymentRequestsByLojaRequest {
    const message = createBaseQueryPaymentRequestsByLojaRequest();
    message.lojaId = object.lojaId ?? 0;
    message.pagination = (object.pagination !== undefined && object.pagination !== null)
      ? PageRequest.fromPartial(object.pagination)
      : undefined;
    return message;
  },
};

function createBaseQueryPaymentRequestsByLojaResponse(): QueryPaymentRequestsByLojaResponse {
  return { paymentRequests: [], pagination: undefined };
}

export const QueryPaymentRequestsByLojaResponse: MessageFns<QueryPaymentRequestsByLojaResponse> = {
  encode(message: QueryPaymentRequestsByLojaResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.paymentRequests) {
      PaymentRequest.encode(v!, writer.uint32(10).fork()).join();
    }
    if (message.pagination !== undefined) {
      PageResponse.encode(message.pagination, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryPaymentRequestsByLojaResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryPaymentRequestsByLojaResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.paymentRequests.push(PaymentRequest.decode(reader, reader.uint32()));
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.pagination = PageResponse.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryPaymentRequestsByLojaResponse {
    return {
      paymentRequests: globalThis.Array.isArray(object?.paymentRequests)
        ? object.paymentRequests.map((e: any) => PaymentRequest.fromJSON(e))
        : globalThis.Array.isArray(object?.payment_requests)
        ? object.payment_requests.map((e: any) => PaymentRequest.fromJSON(e))
        : [],
      pagination: isSet(object.pagination) ? PageResponse.fromJSON(object.pagination) : undefined,
    };
  },

  toJSON(message: QueryPaymentRequestsByLojaResponse): unknown {
    const obj: any = {};
    if (message.paymentRequests?.length) {
      obj.paymentRequests = message.paymentRequests.map((e) => PaymentRequest.toJSON(e));
    }
    if (message.pagination !== undefined) {
      obj.pagination = PageResponse.toJSON(message.pagination);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryPaymentRequestsByLojaResponse>, I>>(
    base?: I,
  ): QueryPaymentRequestsByLojaResponse {
    return QueryPaymentRequestsByLojaResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryPaymentRequestsByLojaResponse>, I>>(
    object: I,
  ): QueryPaymentRequestsByLojaResponse {
    const message = createBaseQueryPaymentRequestsByLojaResponse();
    message.paymentRequests = object.paymentRequests?.map((e) => PaymentRequest.fromPartial(e)) || [];
    message.pagination = (object.pagination !== undefined && object.pagination !== null)
      ? PageResponse.fromPartial(object.pagination)
      : undefined;
    return message;
  },
};

function createBaseQueryPaymentsQRCodeRequest(): QueryPaymentsQRCodeRequest {
  return { requestId: 0, suggestedCertificateId: 0 };
}

export const QueryPaymentsQRCodeRequest: MessageFns<QueryPaymentsQRCodeRequest> = {
  encode(message: QueryPaymentsQRCodeRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.requestId !== 0) {
      writer.uint32(8).uint64(message.requestId);
    }
    if (message.suggestedCertificateId !== 0) {
      writer.uint32(16).uint64(message.suggestedCertificateId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryPaymentsQRCodeRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryPaymentsQRCodeRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.requestId = longToNumber(reader.uint64());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.suggestedCertificateId = longToNumber(reader.uint64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryPaymentsQRCodeRequest {
    return {
      requestId: isSet(object.requestId)
        ? globalThis.Number(object.requestId)
        : isSet(object.request_id)
        ? globalThis.Number(object.request_id)
        : 0,
      suggestedCertificateId: isSet(object.suggestedCertificateId)
        ? globalThis.Number(object.suggestedCertificateId)
        : isSet(object.suggested_certificate_id)
        ? globalThis.Number(object.suggested_certificate_id)
        : 0,
    };
  },

  toJSON(message: QueryPaymentsQRCodeRequest): unknown {
    const obj: any = {};
    if (message.requestId !== 0) {
      obj.requestId = Math.round(message.requestId);
    }
    if (message.suggestedCertificateId !== 0) {
      obj.suggestedCertificateId = Math.round(message.suggestedCertificateId);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryPaymentsQRCodeRequest>, I>>(base?: I): QueryPaymentsQRCodeRequest {
    return QueryPaymentsQRCodeRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryPaymentsQRCodeRequest>, I>>(object: I): QueryPaymentsQRCodeRequest {
    const message = createBaseQueryPaymentsQRCodeRequest();
    message.requestId = object.requestId ?? 0;
    message.suggestedCertificateId = object.suggestedCertificateId ?? 0;
    return message;
  },
};

function createBaseQueryPaymentsQRCodeResponse(): QueryPaymentsQRCodeResponse {
  return { requestId: "", amountUbyx: 0, merchantId: 0, merchantOwner: "", suggestedCertificateId: 0, qrPayload: "" };
}

export const QueryPaymentsQRCodeResponse: MessageFns<QueryPaymentsQRCodeResponse> = {
  encode(message: QueryPaymentsQRCodeResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.requestId !== "") {
      writer.uint32(10).string(message.requestId);
    }
    if (message.amountUbyx !== 0) {
      writer.uint32(16).uint64(message.amountUbyx);
    }
    if (message.merchantId !== 0) {
      writer.uint32(24).uint64(message.merchantId);
    }
    if (message.merchantOwner !== "") {
      writer.uint32(34).string(message.merchantOwner);
    }
    if (message.suggestedCertificateId !== 0) {
      writer.uint32(40).uint64(message.suggestedCertificateId);
    }
    if (message.qrPayload !== "") {
      writer.uint32(50).string(message.qrPayload);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryPaymentsQRCodeResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryPaymentsQRCodeResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.requestId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.amountUbyx = longToNumber(reader.uint64());
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.merchantId = longToNumber(reader.uint64());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.merchantOwner = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.suggestedCertificateId = longToNumber(reader.uint64());
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.qrPayload = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryPaymentsQRCodeResponse {
    return {
      requestId: isSet(object.requestId)
        ? globalThis.String(object.requestId)
        : isSet(object.request_id)
        ? globalThis.String(object.request_id)
        : "",
      amountUbyx: isSet(object.amountUbyx)
        ? globalThis.Number(object.amountUbyx)
        : isSet(object.amount_ubyx)
        ? globalThis.Number(object.amount_ubyx)
        : 0,
      merchantId: isSet(object.merchantId)
        ? globalThis.Number(object.merchantId)
        : isSet(object.merchant_id)
        ? globalThis.Number(object.merchant_id)
        : 0,
      merchantOwner: isSet(object.merchantOwner)
        ? globalThis.String(object.merchantOwner)
        : isSet(object.merchant_owner)
        ? globalThis.String(object.merchant_owner)
        : "",
      suggestedCertificateId: isSet(object.suggestedCertificateId)
        ? globalThis.Number(object.suggestedCertificateId)
        : isSet(object.suggested_certificate_id)
        ? globalThis.Number(object.suggested_certificate_id)
        : 0,
      qrPayload: isSet(object.qrPayload)
        ? globalThis.String(object.qrPayload)
        : isSet(object.qr_payload)
        ? globalThis.String(object.qr_payload)
        : "",
    };
  },

  toJSON(message: QueryPaymentsQRCodeResponse): unknown {
    const obj: any = {};
    if (message.requestId !== "") {
      obj.requestId = message.requestId;
    }
    if (message.amountUbyx !== 0) {
      obj.amountUbyx = Math.round(message.amountUbyx);
    }
    if (message.merchantId !== 0) {
      obj.merchantId = Math.round(message.merchantId);
    }
    if (message.merchantOwner !== "") {
      obj.merchantOwner = message.merchantOwner;
    }
    if (message.suggestedCertificateId !== 0) {
      obj.suggestedCertificateId = Math.round(message.suggestedCertificateId);
    }
    if (message.qrPayload !== "") {
      obj.qrPayload = message.qrPayload;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryPaymentsQRCodeResponse>, I>>(base?: I): QueryPaymentsQRCodeResponse {
    return QueryPaymentsQRCodeResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryPaymentsQRCodeResponse>, I>>(object: I): QueryPaymentsQRCodeResponse {
    const message = createBaseQueryPaymentsQRCodeResponse();
    message.requestId = object.requestId ?? "";
    message.amountUbyx = object.amountUbyx ?? 0;
    message.merchantId = object.merchantId ?? 0;
    message.merchantOwner = object.merchantOwner ?? "";
    message.suggestedCertificateId = object.suggestedCertificateId ?? 0;
    message.qrPayload = object.qrPayload ?? "";
    return message;
  },
};

/** Query defines the gRPC querier service. */
export interface Query {
  /** Parameters queries the parameters of the module. */
  Params(request: QueryParamsRequest): Promise<QueryParamsResponse>;
  /** Retorna um pedido específico. */
  PaymentRequest(request: QueryGetPaymentRequestRequest): Promise<QueryGetPaymentRequestResponse>;
  /** Lista pedidos de uma loja (mais recentes primeiro). */
  PaymentRequestsByLoja(request: QueryPaymentRequestsByLojaRequest): Promise<QueryPaymentRequestsByLojaResponse>;
  /** Retorna um payload JSON compacto para QR (sem frontend). */
  PaymentsQRCode(request: QueryPaymentsQRCodeRequest): Promise<QueryPaymentsQRCodeResponse>;
}

export const QueryServiceName = "byx.payments.v1.Query";
export class QueryClientImpl implements Query {
  private readonly rpc: Rpc;
  private readonly service: string;
  constructor(rpc: Rpc, opts?: { service?: string }) {
    this.service = opts?.service || QueryServiceName;
    this.rpc = rpc;
    this.Params = this.Params.bind(this);
    this.PaymentRequest = this.PaymentRequest.bind(this);
    this.PaymentRequestsByLoja = this.PaymentRequestsByLoja.bind(this);
    this.PaymentsQRCode = this.PaymentsQRCode.bind(this);
  }
  Params(request: QueryParamsRequest): Promise<QueryParamsResponse> {
    const data = QueryParamsRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "Params", data);
    return promise.then((data) => QueryParamsResponse.decode(new BinaryReader(data)));
  }

  PaymentRequest(request: QueryGetPaymentRequestRequest): Promise<QueryGetPaymentRequestResponse> {
    const data = QueryGetPaymentRequestRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "PaymentRequest", data);
    return promise.then((data) => QueryGetPaymentRequestResponse.decode(new BinaryReader(data)));
  }

  PaymentRequestsByLoja(request: QueryPaymentRequestsByLojaRequest): Promise<QueryPaymentRequestsByLojaResponse> {
    const data = QueryPaymentRequestsByLojaRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "PaymentRequestsByLoja", data);
    return promise.then((data) => QueryPaymentRequestsByLojaResponse.decode(new BinaryReader(data)));
  }

  PaymentsQRCode(request: QueryPaymentsQRCodeRequest): Promise<QueryPaymentsQRCodeResponse> {
    const data = QueryPaymentsQRCodeRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "PaymentsQRCode", data);
    return promise.then((data) => QueryPaymentsQRCodeResponse.decode(new BinaryReader(data)));
  }
}

interface Rpc {
  request(service: string, method: string, data: Uint8Array): Promise<Uint8Array>;
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
