version: 1
validation: sovereign
default_denom: ubyx
accounts: 
- name: marcelo
  coins:
  - 200000000000000ubyx
- name: roberta
  coins:
  - 100000000000000ubyx
client:
  openapi:
    path: docs/static/openapi.json
faucet:
  name: roberta
  coins:
  - 5000000ubyx
  - 100000000000ubyx
validators:
- name: marcelo
  bonded: 100000000000000ubyx
- name: validator1
  bonded: 200000000000000ubyx
- name: validator2
  bonded: 100000000000000ubyx

build:
  main: cmd/byxd
