// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: byx/certificados/v1/genesis.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// GenesisState defines the certificados module's genesis state.
type GenesisState struct {
	Params           Params          `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
	Certificates     []Certificate   `protobuf:"bytes,2,rep,name=certificates,proto3" json:"certificates"`
	CertificateCount uint64          `protobuf:"varint,3,opt,name=certificate_count,json=certificateCount,proto3" json:"certificate_count,omitempty"`
	ServiceRecords   []ServiceRecord `protobuf:"bytes,4,rep,name=service_records,json=serviceRecords,proto3" json:"service_records"`
	ServiceCounts    []ServiceCount  `protobuf:"bytes,5,rep,name=service_counts,json=serviceCounts,proto3" json:"service_counts"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c3d54cf50ef9745, []int{0}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

func (m *GenesisState) GetCertificates() []Certificate {
	if m != nil {
		return m.Certificates
	}
	return nil
}

func (m *GenesisState) GetCertificateCount() uint64 {
	if m != nil {
		return m.CertificateCount
	}
	return 0
}

func (m *GenesisState) GetServiceRecords() []ServiceRecord {
	if m != nil {
		return m.ServiceRecords
	}
	return nil
}

func (m *GenesisState) GetServiceCounts() []ServiceCount {
	if m != nil {
		return m.ServiceCounts
	}
	return nil
}

// ServiceCount mantém o número de registros de serviço por certificado.
type ServiceCount struct {
	CertificateId uint64 `protobuf:"varint,1,opt,name=certificate_id,json=certificateId,proto3" json:"certificate_id,omitempty"`
	Count         uint64 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
}

func (m *ServiceCount) Reset()         { *m = ServiceCount{} }
func (m *ServiceCount) String() string { return proto.CompactTextString(m) }
func (*ServiceCount) ProtoMessage()    {}
func (*ServiceCount) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c3d54cf50ef9745, []int{1}
}
func (m *ServiceCount) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ServiceCount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ServiceCount.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ServiceCount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceCount.Merge(m, src)
}
func (m *ServiceCount) XXX_Size() int {
	return m.Size()
}
func (m *ServiceCount) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceCount.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceCount proto.InternalMessageInfo

func (m *ServiceCount) GetCertificateId() uint64 {
	if m != nil {
		return m.CertificateId
	}
	return 0
}

func (m *ServiceCount) GetCount() uint64 {
	if m != nil {
		return m.Count
	}
	return 0
}

func init() {
	proto.RegisterType((*GenesisState)(nil), "byx.certificados.v1.GenesisState")
	proto.RegisterType((*ServiceCount)(nil), "byx.certificados.v1.ServiceCount")
}

func init() { proto.RegisterFile("byx/certificados/v1/genesis.proto", fileDescriptor_4c3d54cf50ef9745) }

var fileDescriptor_4c3d54cf50ef9745 = []byte{
	// 340 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x91, 0xcf, 0x4e, 0xc2, 0x40,
	0x10, 0xc6, 0xbb, 0x50, 0x38, 0x2c, 0x7f, 0xd4, 0x95, 0xc3, 0x06, 0x93, 0xb5, 0x90, 0x90, 0x90,
	0x98, 0xb4, 0x01, 0x4f, 0x5e, 0xe1, 0x60, 0xd4, 0xc4, 0x68, 0xb9, 0x79, 0x21, 0xa5, 0x5d, 0x49,
	0x0f, 0xb2, 0x64, 0x67, 0x25, 0xf0, 0x16, 0x3e, 0x16, 0x47, 0x8e, 0x9e, 0x8c, 0x81, 0xf8, 0x1e,
	0x86, 0xdd, 0xaa, 0xab, 0x69, 0xbc, 0x75, 0xbe, 0xf9, 0xed, 0xf7, 0xcd, 0x74, 0x70, 0x6b, 0xb2,
	0x5a, 0x06, 0x31, 0x97, 0x2a, 0x7d, 0x4c, 0xe3, 0x28, 0x11, 0x10, 0x2c, 0x7a, 0xc1, 0x94, 0xcf,
	0x38, 0xa4, 0xe0, 0xcf, 0xa5, 0x50, 0x82, 0x1c, 0x4f, 0x56, 0x4b, 0xdf, 0x46, 0xfc, 0x45, 0xaf,
	0xd9, 0x98, 0x8a, 0xa9, 0xd0, 0xfd, 0x60, 0xff, 0x65, 0xd0, 0xa6, 0x97, 0xe7, 0x36, 0x8f, 0x64,
	0xf4, 0x94, 0x99, 0x35, 0x3b, 0x79, 0xc4, 0x77, 0xad, 0xb8, 0xc1, 0xda, 0x1f, 0x05, 0x5c, 0xbd,
	0x34, 0x53, 0x8c, 0x54, 0xa4, 0x38, 0xb9, 0xc0, 0x65, 0xe3, 0x43, 0x91, 0x87, 0xba, 0x95, 0xfe,
	0x89, 0x9f, 0x33, 0x95, 0x7f, 0xa7, 0x91, 0x81, 0xbb, 0x7e, 0x3b, 0x75, 0xc2, 0xec, 0x01, 0xb9,
	0xc6, 0x55, 0x2b, 0x00, 0x68, 0xc1, 0x2b, 0x76, 0x2b, 0x7d, 0x2f, 0xd7, 0x60, 0xf8, 0x03, 0x66,
	0x2e, 0xbf, 0xde, 0x92, 0x33, 0x7c, 0x64, 0xd5, 0xe3, 0x58, 0x3c, 0xcf, 0x14, 0x2d, 0x7a, 0xa8,
	0xeb, 0x86, 0x87, 0x56, 0x63, 0xb8, 0xd7, 0xc9, 0x3d, 0x3e, 0x00, 0x2e, 0x17, 0x69, 0xcc, 0xc7,
	0x92, 0xc7, 0x42, 0x26, 0x40, 0x5d, 0x9d, 0xdd, 0xce, 0xcd, 0x1e, 0x19, 0x36, 0xd4, 0x68, 0x96,
	0x5e, 0x07, 0x5b, 0x04, 0x72, 0x8b, 0xbf, 0x14, 0x93, 0x0d, 0xb4, 0xa4, 0x1d, 0x5b, 0xff, 0x39,
	0xea, 0x69, 0x32, 0xc3, 0x1a, 0x58, 0x1a, 0xb4, 0x6f, 0x70, 0xd5, 0x86, 0x48, 0x07, 0xd7, 0xed,
	0xfd, 0xd2, 0x44, 0xff, 0x6e, 0x37, 0xac, 0x59, 0xea, 0x55, 0x42, 0x1a, 0xb8, 0x64, 0x56, 0x2f,
	0xe8, 0xae, 0x29, 0x06, 0xfd, 0xf5, 0x96, 0xa1, 0xcd, 0x96, 0xa1, 0xf7, 0x2d, 0x43, 0x2f, 0x3b,
	0xe6, 0x6c, 0x76, 0xcc, 0x79, 0xdd, 0x31, 0xe7, 0x81, 0xee, 0xaf, 0xfe, 0xe7, 0xee, 0x6a, 0x35,
	0xe7, 0x30, 0x29, 0xeb, 0x7b, 0x9f, 0x7f, 0x06, 0x00, 0x00, 0xff, 0xff, 0xbe, 0xff, 0x4e, 0xb8,
	0x88, 0x02, 0x00, 0x00,
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ServiceCounts) > 0 {
		for iNdEx := len(m.ServiceCounts) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.ServiceCounts[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x2a
		}
	}
	if len(m.ServiceRecords) > 0 {
		for iNdEx := len(m.ServiceRecords) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.ServiceRecords[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if m.CertificateCount != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.CertificateCount))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Certificates) > 0 {
		for iNdEx := len(m.Certificates) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Certificates[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *ServiceCount) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ServiceCount) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ServiceCount) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Count != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.Count))
		i--
		dAtA[i] = 0x10
	}
	if m.CertificateId != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.CertificateId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovGenesis(uint64(l))
	if len(m.Certificates) > 0 {
		for _, e := range m.Certificates {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if m.CertificateCount != 0 {
		n += 1 + sovGenesis(uint64(m.CertificateCount))
	}
	if len(m.ServiceRecords) > 0 {
		for _, e := range m.ServiceRecords {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.ServiceCounts) > 0 {
		for _, e := range m.ServiceCounts {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	return n
}

func (m *ServiceCount) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.CertificateId != 0 {
		n += 1 + sovGenesis(uint64(m.CertificateId))
	}
	if m.Count != 0 {
		n += 1 + sovGenesis(uint64(m.Count))
	}
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Certificates", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Certificates = append(m.Certificates, Certificate{})
			if err := m.Certificates[len(m.Certificates)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CertificateCount", wireType)
			}
			m.CertificateCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CertificateCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ServiceRecords", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ServiceRecords = append(m.ServiceRecords, ServiceRecord{})
			if err := m.ServiceRecords[len(m.ServiceRecords)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ServiceCounts", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ServiceCounts = append(m.ServiceCounts, ServiceCount{})
			if err := m.ServiceCounts[len(m.ServiceCounts)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ServiceCount) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ServiceCount: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ServiceCount: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CertificateId", wireType)
			}
			m.CertificateId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CertificateId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Count", wireType)
			}
			m.Count = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Count |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
