// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: byx/lojas/v1/sale.proto

package types

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Sale struct {
	Id              uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	LojaId          uint64 `protobuf:"varint,2,opt,name=loja_id,json=lojaId,proto3" json:"loja_id,omitempty"`
	Creator         string `protobuf:"bytes,3,opt,name=creator,proto3" json:"creator,omitempty"`
	ValorEmCentavos uint64 `protobuf:"varint,4,opt,name=valor_em_centavos,json=valorEmCentavos,proto3" json:"valor_em_centavos,omitempty"`
	Cliente         string `protobuf:"bytes,5,opt,name=cliente,proto3" json:"cliente,omitempty"`
	CashbackUbyx    uint64 `protobuf:"varint,6,opt,name=cashback_ubyx,json=cashbackUbyx,proto3" json:"cashback_ubyx,omitempty"`
	Timestamp       string `protobuf:"bytes,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	BlockTime       uint64 `protobuf:"varint,8,opt,name=block_time,json=blockTime,proto3" json:"block_time,omitempty"`
}

func (m *Sale) Reset()         { *m = Sale{} }
func (m *Sale) String() string { return proto.CompactTextString(m) }
func (*Sale) ProtoMessage()    {}
func (*Sale) Descriptor() ([]byte, []int) {
	return fileDescriptor_f92e47be3585bed7, []int{0}
}
func (m *Sale) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Sale) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Sale.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Sale) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Sale.Merge(m, src)
}
func (m *Sale) XXX_Size() int {
	return m.Size()
}
func (m *Sale) XXX_DiscardUnknown() {
	xxx_messageInfo_Sale.DiscardUnknown(m)
}

var xxx_messageInfo_Sale proto.InternalMessageInfo

func (m *Sale) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Sale) GetLojaId() uint64 {
	if m != nil {
		return m.LojaId
	}
	return 0
}

func (m *Sale) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *Sale) GetValorEmCentavos() uint64 {
	if m != nil {
		return m.ValorEmCentavos
	}
	return 0
}

func (m *Sale) GetCliente() string {
	if m != nil {
		return m.Cliente
	}
	return ""
}

func (m *Sale) GetCashbackUbyx() uint64 {
	if m != nil {
		return m.CashbackUbyx
	}
	return 0
}

func (m *Sale) GetTimestamp() string {
	if m != nil {
		return m.Timestamp
	}
	return ""
}

func (m *Sale) GetBlockTime() uint64 {
	if m != nil {
		return m.BlockTime
	}
	return 0
}

type SalesCountState struct {
	LastHeight int64  `protobuf:"varint,1,opt,name=last_height,json=lastHeight,proto3" json:"last_height,omitempty"`
	Count      uint32 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
}

func (m *SalesCountState) Reset()         { *m = SalesCountState{} }
func (m *SalesCountState) String() string { return proto.CompactTextString(m) }
func (*SalesCountState) ProtoMessage()    {}
func (*SalesCountState) Descriptor() ([]byte, []int) {
	return fileDescriptor_f92e47be3585bed7, []int{1}
}
func (m *SalesCountState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SalesCountState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SalesCountState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SalesCountState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SalesCountState.Merge(m, src)
}
func (m *SalesCountState) XXX_Size() int {
	return m.Size()
}
func (m *SalesCountState) XXX_DiscardUnknown() {
	xxx_messageInfo_SalesCountState.DiscardUnknown(m)
}

var xxx_messageInfo_SalesCountState proto.InternalMessageInfo

func (m *SalesCountState) GetLastHeight() int64 {
	if m != nil {
		return m.LastHeight
	}
	return 0
}

func (m *SalesCountState) GetCount() uint32 {
	if m != nil {
		return m.Count
	}
	return 0
}

type SalesSummary struct {
	LojaId                uint64 `protobuf:"varint,1,opt,name=loja_id,json=lojaId,proto3" json:"loja_id,omitempty"`
	TotalVendas           uint64 `protobuf:"varint,2,opt,name=total_vendas,json=totalVendas,proto3" json:"total_vendas,omitempty"`
	TotalValorEmCentavos  uint64 `protobuf:"varint,3,opt,name=total_valor_em_centavos,json=totalValorEmCentavos,proto3" json:"total_valor_em_centavos,omitempty"`
	TotalCashbackUbyx     uint64 `protobuf:"varint,4,opt,name=total_cashback_ubyx,json=totalCashbackUbyx,proto3" json:"total_cashback_ubyx,omitempty"`
	TicketMedioEmCentavos uint64 `protobuf:"varint,5,opt,name=ticket_medio_em_centavos,json=ticketMedioEmCentavos,proto3" json:"ticket_medio_em_centavos,omitempty"`
}

func (m *SalesSummary) Reset()         { *m = SalesSummary{} }
func (m *SalesSummary) String() string { return proto.CompactTextString(m) }
func (*SalesSummary) ProtoMessage()    {}
func (*SalesSummary) Descriptor() ([]byte, []int) {
	return fileDescriptor_f92e47be3585bed7, []int{2}
}
func (m *SalesSummary) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SalesSummary) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SalesSummary.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SalesSummary) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SalesSummary.Merge(m, src)
}
func (m *SalesSummary) XXX_Size() int {
	return m.Size()
}
func (m *SalesSummary) XXX_DiscardUnknown() {
	xxx_messageInfo_SalesSummary.DiscardUnknown(m)
}

var xxx_messageInfo_SalesSummary proto.InternalMessageInfo

func (m *SalesSummary) GetLojaId() uint64 {
	if m != nil {
		return m.LojaId
	}
	return 0
}

func (m *SalesSummary) GetTotalVendas() uint64 {
	if m != nil {
		return m.TotalVendas
	}
	return 0
}

func (m *SalesSummary) GetTotalValorEmCentavos() uint64 {
	if m != nil {
		return m.TotalValorEmCentavos
	}
	return 0
}

func (m *SalesSummary) GetTotalCashbackUbyx() uint64 {
	if m != nil {
		return m.TotalCashbackUbyx
	}
	return 0
}

func (m *SalesSummary) GetTicketMedioEmCentavos() uint64 {
	if m != nil {
		return m.TicketMedioEmCentavos
	}
	return 0
}

func init() {
	proto.RegisterType((*Sale)(nil), "byx.lojas.v1.Sale")
	proto.RegisterType((*SalesCountState)(nil), "byx.lojas.v1.SalesCountState")
	proto.RegisterType((*SalesSummary)(nil), "byx.lojas.v1.SalesSummary")
}

func init() { proto.RegisterFile("byx/lojas/v1/sale.proto", fileDescriptor_f92e47be3585bed7) }

var fileDescriptor_f92e47be3585bed7 = []byte{
	// 417 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x92, 0xbf, 0x8e, 0x13, 0x31,
	0x10, 0x87, 0xe3, 0xfc, 0x25, 0x73, 0x39, 0x4e, 0x31, 0x87, 0xe2, 0x02, 0x96, 0x23, 0x34, 0x27,
	0x90, 0x12, 0x9d, 0x10, 0xa2, 0x27, 0x42, 0x3a, 0x0a, 0x9a, 0x04, 0x28, 0x68, 0x56, 0xde, 0x5d,
	0x8b, 0x98, 0xd8, 0x71, 0xb4, 0x9e, 0xac, 0xb2, 0x6f, 0xc1, 0x63, 0x51, 0x5e, 0x49, 0x89, 0x92,
	0x8e, 0x8e, 0x37, 0x40, 0x9e, 0x4d, 0x74, 0x17, 0xae, 0x9c, 0x6f, 0x66, 0x7e, 0x96, 0x3f, 0x0d,
	0x0c, 0x92, 0x72, 0x33, 0x36, 0xee, 0xbb, 0xf4, 0xe3, 0xe2, 0x6a, 0xec, 0xa5, 0x51, 0xa3, 0x55,
	0xee, 0xd0, 0xf1, 0x5e, 0x52, 0x6e, 0x46, 0xd4, 0x18, 0x15, 0x57, 0xc3, 0xbf, 0x0c, 0x9a, 0x33,
	0x69, 0x14, 0x7f, 0x08, 0x75, 0x9d, 0x09, 0x76, 0xc1, 0x2e, 0x9b, 0xd3, 0xba, 0xce, 0xf8, 0x00,
	0x3a, 0x61, 0x28, 0xd6, 0x99, 0xa8, 0x13, 0x6c, 0x87, 0xf2, 0x43, 0xc6, 0x05, 0x74, 0xd2, 0x5c,
	0x49, 0x74, 0xb9, 0x68, 0x5c, 0xb0, 0xcb, 0xee, 0xf4, 0x50, 0xf2, 0x97, 0xd0, 0x2f, 0xa4, 0x71,
	0x79, 0xac, 0x6c, 0x9c, 0xaa, 0x25, 0xca, 0xc2, 0x79, 0xd1, 0xa4, 0xe5, 0x33, 0x6a, 0xbc, 0xb7,
	0x93, 0x3d, 0xa6, 0x14, 0xa3, 0xd5, 0x12, 0x95, 0x68, 0xed, 0x53, 0xaa, 0x92, 0xbf, 0x80, 0xd3,
	0x54, 0xfa, 0x79, 0x22, 0xd3, 0x45, 0xbc, 0x4e, 0xca, 0x8d, 0x68, 0x53, 0x42, 0xef, 0x00, 0x3f,
	0x27, 0xe5, 0x86, 0x3f, 0x81, 0x2e, 0x6a, 0xab, 0x3c, 0x4a, 0xbb, 0x12, 0x1d, 0x0a, 0xb8, 0x05,
	0xfc, 0x29, 0x40, 0x62, 0x5c, 0xba, 0x88, 0x03, 0x12, 0x0f, 0x68, 0xbf, 0x4b, 0xe4, 0x93, 0xb6,
	0x6a, 0x78, 0x0d, 0x67, 0xe1, 0xcb, 0x7e, 0xe2, 0xd6, 0x4b, 0x9c, 0xa1, 0x44, 0xc5, 0x9f, 0xc1,
	0x89, 0x91, 0x1e, 0xe3, 0xb9, 0xd2, 0xdf, 0xe6, 0x48, 0x1a, 0x1a, 0x53, 0x08, 0xe8, 0x9a, 0x08,
	0x3f, 0x87, 0x56, 0x1a, 0xc6, 0x49, 0xc6, 0xe9, 0xb4, 0x2a, 0x86, 0x7f, 0x18, 0xf4, 0x28, 0x6a,
	0xb6, 0xb6, 0x56, 0xe6, 0xe5, 0x5d, 0x6b, 0xec, 0xc8, 0xda, 0x73, 0xe8, 0xa1, 0x43, 0x69, 0xe2,
	0x42, 0x2d, 0x33, 0xe9, 0xf7, 0x4e, 0x4f, 0x88, 0x7d, 0x21, 0xc4, 0xdf, 0xc0, 0x60, 0x3f, 0x72,
	0x4f, 0x62, 0x83, 0xa6, 0xcf, 0xab, 0xe9, 0xff, 0x4c, 0x8e, 0xe0, 0x51, 0xb5, 0x76, 0x6c, 0xad,
	0xf2, 0xde, 0xa7, 0xd6, 0xe4, 0xae, 0xba, 0xb7, 0x20, 0x50, 0xa7, 0x0b, 0x85, 0xb1, 0x55, 0x99,
	0x76, 0x47, 0xef, 0xb4, 0x68, 0xe9, 0x71, 0xd5, 0xff, 0x18, 0xda, 0xb7, 0x0f, 0xbd, 0x7b, 0xf5,
	0x73, 0x1b, 0xb1, 0x9b, 0x6d, 0xc4, 0x7e, 0x6f, 0x23, 0xf6, 0x63, 0x17, 0xd5, 0x6e, 0x76, 0x51,
	0xed, 0xd7, 0x2e, 0xaa, 0x7d, 0xed, 0x87, 0x5b, 0x3b, 0x5c, 0x1b, 0x96, 0x2b, 0xe5, 0x93, 0x36,
	0x1d, 0xdb, 0xeb, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x3c, 0x18, 0x0d, 0x3e, 0x87, 0x02, 0x00,
	0x00,
}

func (m *Sale) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Sale) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Sale) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.BlockTime != 0 {
		i = encodeVarintSale(dAtA, i, uint64(m.BlockTime))
		i--
		dAtA[i] = 0x40
	}
	if len(m.Timestamp) > 0 {
		i -= len(m.Timestamp)
		copy(dAtA[i:], m.Timestamp)
		i = encodeVarintSale(dAtA, i, uint64(len(m.Timestamp)))
		i--
		dAtA[i] = 0x3a
	}
	if m.CashbackUbyx != 0 {
		i = encodeVarintSale(dAtA, i, uint64(m.CashbackUbyx))
		i--
		dAtA[i] = 0x30
	}
	if len(m.Cliente) > 0 {
		i -= len(m.Cliente)
		copy(dAtA[i:], m.Cliente)
		i = encodeVarintSale(dAtA, i, uint64(len(m.Cliente)))
		i--
		dAtA[i] = 0x2a
	}
	if m.ValorEmCentavos != 0 {
		i = encodeVarintSale(dAtA, i, uint64(m.ValorEmCentavos))
		i--
		dAtA[i] = 0x20
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintSale(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0x1a
	}
	if m.LojaId != 0 {
		i = encodeVarintSale(dAtA, i, uint64(m.LojaId))
		i--
		dAtA[i] = 0x10
	}
	if m.Id != 0 {
		i = encodeVarintSale(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *SalesCountState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SalesCountState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SalesCountState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Count != 0 {
		i = encodeVarintSale(dAtA, i, uint64(m.Count))
		i--
		dAtA[i] = 0x10
	}
	if m.LastHeight != 0 {
		i = encodeVarintSale(dAtA, i, uint64(m.LastHeight))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *SalesSummary) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SalesSummary) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SalesSummary) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.TicketMedioEmCentavos != 0 {
		i = encodeVarintSale(dAtA, i, uint64(m.TicketMedioEmCentavos))
		i--
		dAtA[i] = 0x28
	}
	if m.TotalCashbackUbyx != 0 {
		i = encodeVarintSale(dAtA, i, uint64(m.TotalCashbackUbyx))
		i--
		dAtA[i] = 0x20
	}
	if m.TotalValorEmCentavos != 0 {
		i = encodeVarintSale(dAtA, i, uint64(m.TotalValorEmCentavos))
		i--
		dAtA[i] = 0x18
	}
	if m.TotalVendas != 0 {
		i = encodeVarintSale(dAtA, i, uint64(m.TotalVendas))
		i--
		dAtA[i] = 0x10
	}
	if m.LojaId != 0 {
		i = encodeVarintSale(dAtA, i, uint64(m.LojaId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintSale(dAtA []byte, offset int, v uint64) int {
	offset -= sovSale(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Sale) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovSale(uint64(m.Id))
	}
	if m.LojaId != 0 {
		n += 1 + sovSale(uint64(m.LojaId))
	}
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovSale(uint64(l))
	}
	if m.ValorEmCentavos != 0 {
		n += 1 + sovSale(uint64(m.ValorEmCentavos))
	}
	l = len(m.Cliente)
	if l > 0 {
		n += 1 + l + sovSale(uint64(l))
	}
	if m.CashbackUbyx != 0 {
		n += 1 + sovSale(uint64(m.CashbackUbyx))
	}
	l = len(m.Timestamp)
	if l > 0 {
		n += 1 + l + sovSale(uint64(l))
	}
	if m.BlockTime != 0 {
		n += 1 + sovSale(uint64(m.BlockTime))
	}
	return n
}

func (m *SalesCountState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.LastHeight != 0 {
		n += 1 + sovSale(uint64(m.LastHeight))
	}
	if m.Count != 0 {
		n += 1 + sovSale(uint64(m.Count))
	}
	return n
}

func (m *SalesSummary) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.LojaId != 0 {
		n += 1 + sovSale(uint64(m.LojaId))
	}
	if m.TotalVendas != 0 {
		n += 1 + sovSale(uint64(m.TotalVendas))
	}
	if m.TotalValorEmCentavos != 0 {
		n += 1 + sovSale(uint64(m.TotalValorEmCentavos))
	}
	if m.TotalCashbackUbyx != 0 {
		n += 1 + sovSale(uint64(m.TotalCashbackUbyx))
	}
	if m.TicketMedioEmCentavos != 0 {
		n += 1 + sovSale(uint64(m.TicketMedioEmCentavos))
	}
	return n
}

func sovSale(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozSale(x uint64) (n int) {
	return sovSale(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Sale) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSale
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Sale: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Sale: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSale
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LojaId", wireType)
			}
			m.LojaId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSale
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LojaId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSale
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSale
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSale
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValorEmCentavos", wireType)
			}
			m.ValorEmCentavos = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSale
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ValorEmCentavos |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Cliente", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSale
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSale
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSale
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Cliente = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CashbackUbyx", wireType)
			}
			m.CashbackUbyx = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSale
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CashbackUbyx |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Timestamp", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSale
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSale
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSale
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Timestamp = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlockTime", wireType)
			}
			m.BlockTime = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSale
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BlockTime |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipSale(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSale
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SalesCountState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSale
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SalesCountState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SalesCountState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastHeight", wireType)
			}
			m.LastHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSale
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LastHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Count", wireType)
			}
			m.Count = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSale
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Count |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipSale(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSale
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SalesSummary) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSale
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SalesSummary: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SalesSummary: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LojaId", wireType)
			}
			m.LojaId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSale
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LojaId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalVendas", wireType)
			}
			m.TotalVendas = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSale
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TotalVendas |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalValorEmCentavos", wireType)
			}
			m.TotalValorEmCentavos = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSale
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TotalValorEmCentavos |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalCashbackUbyx", wireType)
			}
			m.TotalCashbackUbyx = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSale
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TotalCashbackUbyx |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TicketMedioEmCentavos", wireType)
			}
			m.TicketMedioEmCentavos = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSale
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TicketMedioEmCentavos |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipSale(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSale
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipSale(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowSale
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowSale
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowSale
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthSale
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupSale
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthSale
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthSale        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowSale          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupSale = fmt.Errorf("proto: unexpected end of group")
)
