// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: byx/lojas/v1/merchant.proto

package types

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Merchant defines the Merchant message.
type Merchant struct {
	Id       uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Nome     string `protobuf:"bytes,2,opt,name=nome,proto3" json:"nome,omitempty"`
	Endereco string `protobuf:"bytes,3,opt,name=endereco,proto3" json:"endereco,omitempty"`
	Cpfcnpj  string `protobuf:"bytes,4,opt,name=cpfcnpj,proto3" json:"cpfcnpj,omitempty"`
	Telefone string `protobuf:"bytes,5,opt,name=telefone,proto3" json:"telefone,omitempty"`
	Saldo    string `protobuf:"bytes,6,opt,name=saldo,proto3" json:"saldo,omitempty"`
	Creator  string `protobuf:"bytes,7,opt,name=creator,proto3" json:"creator,omitempty"`
}

func (m *Merchant) Reset()         { *m = Merchant{} }
func (m *Merchant) String() string { return proto.CompactTextString(m) }
func (*Merchant) ProtoMessage()    {}
func (*Merchant) Descriptor() ([]byte, []int) {
	return fileDescriptor_8fc769c04c0016a3, []int{0}
}
func (m *Merchant) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Merchant) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Merchant.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Merchant) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Merchant.Merge(m, src)
}
func (m *Merchant) XXX_Size() int {
	return m.Size()
}
func (m *Merchant) XXX_DiscardUnknown() {
	xxx_messageInfo_Merchant.DiscardUnknown(m)
}

var xxx_messageInfo_Merchant proto.InternalMessageInfo

func (m *Merchant) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Merchant) GetNome() string {
	if m != nil {
		return m.Nome
	}
	return ""
}

func (m *Merchant) GetEndereco() string {
	if m != nil {
		return m.Endereco
	}
	return ""
}

func (m *Merchant) GetCpfcnpj() string {
	if m != nil {
		return m.Cpfcnpj
	}
	return ""
}

func (m *Merchant) GetTelefone() string {
	if m != nil {
		return m.Telefone
	}
	return ""
}

func (m *Merchant) GetSaldo() string {
	if m != nil {
		return m.Saldo
	}
	return ""
}

func (m *Merchant) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func init() {
	proto.RegisterType((*Merchant)(nil), "byx.lojas.v1.Merchant")
}

func init() { proto.RegisterFile("byx/lojas/v1/merchant.proto", fileDescriptor_8fc769c04c0016a3) }

var fileDescriptor_8fc769c04c0016a3 = []byte{
	// 228 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x4e, 0xaa, 0xac, 0xd0,
	0xcf, 0xc9, 0xcf, 0x4a, 0x2c, 0xd6, 0x2f, 0x33, 0xd4, 0xcf, 0x4d, 0x2d, 0x4a, 0xce, 0x48, 0xcc,
	0x2b, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x49, 0xaa, 0xac, 0xd0, 0x03, 0x4b, 0xea,
	0x95, 0x19, 0x2a, 0x6d, 0x60, 0xe4, 0xe2, 0xf0, 0x85, 0x2a, 0x10, 0xe2, 0xe3, 0x62, 0xca, 0x4c,
	0x91, 0x60, 0x54, 0x60, 0xd4, 0x60, 0x09, 0x62, 0xca, 0x4c, 0x11, 0x12, 0xe2, 0x62, 0xc9, 0xcb,
	0xcf, 0x4d, 0x95, 0x60, 0x52, 0x60, 0xd4, 0xe0, 0x0c, 0x02, 0xb3, 0x85, 0xa4, 0xb8, 0x38, 0x52,
	0xf3, 0x52, 0x52, 0x8b, 0x52, 0x93, 0xf3, 0x25, 0x98, 0xc1, 0xe2, 0x70, 0xbe, 0x90, 0x04, 0x17,
	0x7b, 0x72, 0x41, 0x5a, 0x72, 0x5e, 0x41, 0x96, 0x04, 0x0b, 0x58, 0x0a, 0xc6, 0x05, 0xe9, 0x2a,
	0x49, 0xcd, 0x49, 0x4d, 0xcb, 0xcf, 0x4b, 0x95, 0x60, 0x85, 0xe8, 0x82, 0xf1, 0x85, 0x44, 0xb8,
	0x58, 0x8b, 0x13, 0x73, 0x52, 0xf2, 0x25, 0xd8, 0xc0, 0x12, 0x10, 0x0e, 0xd8, 0xac, 0xa2, 0xd4,
	0xc4, 0x92, 0xfc, 0x22, 0x09, 0x76, 0xa8, 0x59, 0x10, 0xae, 0x93, 0xf6, 0x89, 0x47, 0x72, 0x8c,
	0x17, 0x1e, 0xc9, 0x31, 0x3e, 0x78, 0x24, 0xc7, 0x38, 0xe1, 0xb1, 0x1c, 0xc3, 0x85, 0xc7, 0x72,
	0x0c, 0x37, 0x1e, 0xcb, 0x31, 0x44, 0x09, 0x82, 0xfc, 0x0d, 0xf3, 0x79, 0x49, 0x65, 0x41, 0x6a,
	0x71, 0x12, 0x1b, 0xd8, 0xd3, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0xf2, 0xaf, 0x83, 0xab,
	0x13, 0x01, 0x00, 0x00,
}

func (m *Merchant) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Merchant) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Merchant) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintMerchant(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.Saldo) > 0 {
		i -= len(m.Saldo)
		copy(dAtA[i:], m.Saldo)
		i = encodeVarintMerchant(dAtA, i, uint64(len(m.Saldo)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.Telefone) > 0 {
		i -= len(m.Telefone)
		copy(dAtA[i:], m.Telefone)
		i = encodeVarintMerchant(dAtA, i, uint64(len(m.Telefone)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Cpfcnpj) > 0 {
		i -= len(m.Cpfcnpj)
		copy(dAtA[i:], m.Cpfcnpj)
		i = encodeVarintMerchant(dAtA, i, uint64(len(m.Cpfcnpj)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Endereco) > 0 {
		i -= len(m.Endereco)
		copy(dAtA[i:], m.Endereco)
		i = encodeVarintMerchant(dAtA, i, uint64(len(m.Endereco)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Nome) > 0 {
		i -= len(m.Nome)
		copy(dAtA[i:], m.Nome)
		i = encodeVarintMerchant(dAtA, i, uint64(len(m.Nome)))
		i--
		dAtA[i] = 0x12
	}
	if m.Id != 0 {
		i = encodeVarintMerchant(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintMerchant(dAtA []byte, offset int, v uint64) int {
	offset -= sovMerchant(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Merchant) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovMerchant(uint64(m.Id))
	}
	l = len(m.Nome)
	if l > 0 {
		n += 1 + l + sovMerchant(uint64(l))
	}
	l = len(m.Endereco)
	if l > 0 {
		n += 1 + l + sovMerchant(uint64(l))
	}
	l = len(m.Cpfcnpj)
	if l > 0 {
		n += 1 + l + sovMerchant(uint64(l))
	}
	l = len(m.Telefone)
	if l > 0 {
		n += 1 + l + sovMerchant(uint64(l))
	}
	l = len(m.Saldo)
	if l > 0 {
		n += 1 + l + sovMerchant(uint64(l))
	}
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovMerchant(uint64(l))
	}
	return n
}

func sovMerchant(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozMerchant(x uint64) (n int) {
	return sovMerchant(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Merchant) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMerchant
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Merchant: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Merchant: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMerchant
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Nome", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMerchant
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMerchant
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMerchant
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Nome = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Endereco", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMerchant
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMerchant
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMerchant
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Endereco = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Cpfcnpj", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMerchant
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMerchant
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMerchant
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Cpfcnpj = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Telefone", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMerchant
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMerchant
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMerchant
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Telefone = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Saldo", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMerchant
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMerchant
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMerchant
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Saldo = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMerchant
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMerchant
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMerchant
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMerchant(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMerchant
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipMerchant(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowMerchant
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMerchant
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMerchant
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthMerchant
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupMerchant
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthMerchant
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthMerchant        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowMerchant          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupMerchant = fmt.Errorf("proto: unexpected end of group")
)
