// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: byx/lojas/v1/params.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Parâmetros do módulo lojas
type Params struct {
	// Endereço bech32 que pode chamar o faucet (opcional)
	FaucetAdmin string `protobuf:"bytes,1,opt,name=faucet_admin,json=faucetAdmin,proto3" json:"faucet_admin,omitempty"`
	// Liga/desliga o faucet no módulo
	FaucetEnabled bool `protobuf:"varint,2,opt,name=faucet_enabled,json=faucetEnabled,proto3" json:"faucet_enabled,omitempty"`
	// Limite por transação do faucet (Int em string, ex "1000")
	FaucetMaxPerTx string `protobuf:"bytes,3,opt,name=faucet_max_per_tx,json=faucetMaxPerTx,proto3" json:"faucet_max_per_tx,omitempty"`
	// Cashback em micro BYX por real gasto (ex.: 2500 = 0.0025 BYX/R$1)
	CashbackRateMicroByxPerReal uint64 `protobuf:"varint,4,opt,name=cashback_rate_micro_byx_per_real,json=cashbackRateMicroByxPerReal,proto3" json:"cashback_rate_micro_byx_per_real,omitempty"`
	// Limite máximo de valor de venda em centavos (anti-abuso)
	MaxValorVendaEmCentavos uint64 `protobuf:"varint,5,opt,name=max_valor_venda_em_centavos,json=maxValorVendaEmCentavos,proto3" json:"max_valor_venda_em_centavos,omitempty"`
	// Limite máximo de cashback por venda em micro BYX
	MaxCashbackMicroByxPorVenda uint64 `protobuf:"varint,6,opt,name=max_cashback_micro_byx_por_venda,json=maxCashbackMicroByxPorVenda,proto3" json:"max_cashback_micro_byx_por_venda,omitempty"`
	// Limite diário de cashback por loja (micro BYX)
	MaxCashbackDailyPerLojaMicrobyx uint64 `protobuf:"varint,7,opt,name=max_cashback_daily_per_loja_microbyx,json=maxCashbackDailyPerLojaMicrobyx,proto3" json:"max_cashback_daily_per_loja_microbyx,omitempty"`
	// Limite de vendas por bloco por loja
	MaxSalesPerBlockPerLoja uint32 `protobuf:"varint,8,opt,name=max_sales_per_block_per_loja,json=maxSalesPerBlockPerLoja,proto3" json:"max_sales_per_block_per_loja,omitempty"`
	// Habilita/desabilita verificações de limite
	LimitsEnabled bool `protobuf:"varint,9,opt,name=limits_enabled,json=limitsEnabled,proto3" json:"limits_enabled,omitempty"`
	// Quantos dias manter acumulador diário antes de limpar (MVP simples)
	CashbackDailyRetentionDays uint32 `protobuf:"varint,10,opt,name=cashback_daily_retention_days,json=cashbackDailyRetentionDays,proto3" json:"cashback_daily_retention_days,omitempty"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_6652bfa2d58d1d30, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetFaucetAdmin() string {
	if m != nil {
		return m.FaucetAdmin
	}
	return ""
}

func (m *Params) GetFaucetEnabled() bool {
	if m != nil {
		return m.FaucetEnabled
	}
	return false
}

func (m *Params) GetFaucetMaxPerTx() string {
	if m != nil {
		return m.FaucetMaxPerTx
	}
	return ""
}

func (m *Params) GetCashbackRateMicroByxPerReal() uint64 {
	if m != nil {
		return m.CashbackRateMicroByxPerReal
	}
	return 0
}

func (m *Params) GetMaxValorVendaEmCentavos() uint64 {
	if m != nil {
		return m.MaxValorVendaEmCentavos
	}
	return 0
}

func (m *Params) GetMaxCashbackMicroByxPorVenda() uint64 {
	if m != nil {
		return m.MaxCashbackMicroByxPorVenda
	}
	return 0
}

func (m *Params) GetMaxCashbackDailyPerLojaMicrobyx() uint64 {
	if m != nil {
		return m.MaxCashbackDailyPerLojaMicrobyx
	}
	return 0
}

func (m *Params) GetMaxSalesPerBlockPerLoja() uint32 {
	if m != nil {
		return m.MaxSalesPerBlockPerLoja
	}
	return 0
}

func (m *Params) GetLimitsEnabled() bool {
	if m != nil {
		return m.LimitsEnabled
	}
	return false
}

func (m *Params) GetCashbackDailyRetentionDays() uint32 {
	if m != nil {
		return m.CashbackDailyRetentionDays
	}
	return 0
}

func init() {
	proto.RegisterType((*Params)(nil), "byx.lojas.v1.Params")
}

func init() { proto.RegisterFile("byx/lojas/v1/params.proto", fileDescriptor_6652bfa2d58d1d30) }

var fileDescriptor_6652bfa2d58d1d30 = []byte{
	// 475 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x92, 0xcf, 0x6e, 0xd3, 0x40,
	0x10, 0x87, 0x63, 0x08, 0xa1, 0x5d, 0x5a, 0xa4, 0x5a, 0x95, 0xd8, 0xa6, 0x60, 0x22, 0x04, 0x52,
	0x10, 0x22, 0x51, 0xc5, 0x11, 0x38, 0x24, 0x6d, 0x6e, 0x44, 0x8a, 0x5c, 0xd4, 0x03, 0x97, 0xd5,
	0xd8, 0x1e, 0x82, 0x5b, 0xaf, 0x37, 0xda, 0x5d, 0x2c, 0xfb, 0x2d, 0x78, 0x18, 0x1e, 0x82, 0x63,
	0xc5, 0x09, 0x89, 0x0b, 0x4a, 0x5e, 0x04, 0xed, 0x1f, 0x47, 0x81, 0x9b, 0xbd, 0xf3, 0xcd, 0xb7,
	0xbf, 0xd5, 0x0c, 0x39, 0x49, 0x9a, 0x7a, 0x5c, 0x88, 0x6b, 0x50, 0xe3, 0xea, 0x6c, 0xbc, 0x02,
	0x09, 0x5c, 0x8d, 0x56, 0x52, 0x68, 0x11, 0x1e, 0x24, 0x4d, 0x3d, 0xb2, 0xa5, 0x51, 0x75, 0xd6,
	0x3f, 0x5e, 0x8a, 0xa5, 0xb0, 0x85, 0xb1, 0xf9, 0x72, 0x4c, 0xff, 0x24, 0x15, 0x8a, 0x0b, 0xc5,
	0x5c, 0xc1, 0xfd, 0xb8, 0xd2, 0xb3, 0xdf, 0x5d, 0xd2, 0x5b, 0x58, 0x5f, 0xf8, 0x96, 0x1c, 0x7c,
	0x86, 0xaf, 0x29, 0x6a, 0x06, 0x19, 0xcf, 0x4b, 0x1a, 0x0c, 0x82, 0xe1, 0xfe, 0x94, 0xfe, 0xfc,
	0xfe, 0xfa, 0xd8, 0xb7, 0x4c, 0xb2, 0x4c, 0xa2, 0x52, 0x97, 0x5a, 0xe6, 0xe5, 0x32, 0x7e, 0xe0,
	0xe8, 0x89, 0x81, 0xc3, 0x17, 0xe4, 0xa1, 0x6f, 0xc6, 0x12, 0x92, 0x02, 0x33, 0x7a, 0x67, 0x10,
	0x0c, 0xf7, 0xe2, 0x43, 0x77, 0x3a, 0x73, 0x87, 0xe1, 0x4b, 0x72, 0xe4, 0x31, 0x0e, 0x35, 0x5b,
	0xa1, 0x64, 0xba, 0xa6, 0x77, 0xcd, 0x45, 0xb1, 0xef, 0x9f, 0x43, 0xbd, 0x40, 0xf9, 0xb1, 0x0e,
	0x67, 0x64, 0x90, 0x82, 0xfa, 0x92, 0x40, 0x7a, 0xc3, 0x24, 0x68, 0x64, 0x3c, 0x4f, 0xa5, 0x60,
	0x49, 0xe3, 0xfa, 0x24, 0x42, 0x41, 0xbb, 0x83, 0x60, 0xd8, 0x8d, 0x4f, 0x5b, 0x2e, 0x06, 0x8d,
	0x73, 0x43, 0x4d, 0x1b, 0x23, 0x89, 0x11, 0x8a, 0xf0, 0x1d, 0x39, 0x35, 0x57, 0x55, 0x50, 0x08,
	0xc9, 0x2a, 0x2c, 0x33, 0x60, 0xc8, 0x59, 0x8a, 0xa5, 0x86, 0x4a, 0x28, 0x7a, 0xcf, 0x1a, 0x1e,
	0x71, 0xa8, 0xaf, 0x0c, 0x71, 0x65, 0x80, 0x19, 0x3f, 0xf7, 0x65, 0x13, 0xc2, 0x74, 0x6f, 0x83,
	0xec, 0x64, 0x68, 0x75, 0xb4, 0xe7, 0x42, 0x70, 0xa8, 0xcf, 0x3d, 0xb6, 0xcd, 0xe0, 0x85, 0xe1,
	0x9c, 0x3c, 0xff, 0x47, 0x93, 0x41, 0x5e, 0x34, 0xf6, 0x19, 0x66, 0x72, 0xce, 0x9a, 0x34, 0x35,
	0xbd, 0x6f, 0x55, 0x4f, 0x77, 0x54, 0x17, 0x86, 0x5c, 0xa0, 0xfc, 0x20, 0xae, 0x61, 0xee, 0xb1,
	0xf0, 0x3d, 0x79, 0x6c, 0x74, 0x0a, 0x0a, 0x54, 0xd6, 0x92, 0x14, 0x22, 0xbd, 0xd9, 0xfa, 0xe8,
	0xde, 0x20, 0x18, 0x1e, 0xda, 0x47, 0x5d, 0x1a, 0x64, 0x81, 0x72, 0x6a, 0x00, 0xaf, 0x31, 0xb3,
	0x2a, 0x72, 0x9e, 0x6b, 0xb5, 0x9d, 0xd5, 0xbe, 0x9b, 0x95, 0x3b, 0x6d, 0x67, 0x35, 0x21, 0x4f,
	0xfe, 0x0b, 0x2c, 0x51, 0x63, 0xa9, 0x73, 0x51, 0xb2, 0x0c, 0x1a, 0x45, 0x89, 0xbd, 0xa6, 0x9f,
	0xee, 0x46, 0x8d, 0x5b, 0xe4, 0x02, 0x1a, 0x35, 0x7d, 0xf5, 0x63, 0x1d, 0x05, 0xb7, 0xeb, 0x28,
	0xf8, 0xb3, 0x8e, 0x82, 0x6f, 0x9b, 0xa8, 0x73, 0xbb, 0x89, 0x3a, 0xbf, 0x36, 0x51, 0xe7, 0xd3,
	0x91, 0xd9, 0xe8, 0x76, 0xa7, 0x75, 0xb3, 0x42, 0x95, 0xf4, 0xec, 0x46, 0xbe, 0xf9, 0x1b, 0x00,
	0x00, 0xff, 0xff, 0xee, 0xad, 0xda, 0x00, 0xed, 0x02, 0x00, 0x00,
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.CashbackDailyRetentionDays != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.CashbackDailyRetentionDays))
		i--
		dAtA[i] = 0x50
	}
	if m.LimitsEnabled {
		i--
		if m.LimitsEnabled {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x48
	}
	if m.MaxSalesPerBlockPerLoja != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MaxSalesPerBlockPerLoja))
		i--
		dAtA[i] = 0x40
	}
	if m.MaxCashbackDailyPerLojaMicrobyx != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MaxCashbackDailyPerLojaMicrobyx))
		i--
		dAtA[i] = 0x38
	}
	if m.MaxCashbackMicroByxPorVenda != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MaxCashbackMicroByxPorVenda))
		i--
		dAtA[i] = 0x30
	}
	if m.MaxValorVendaEmCentavos != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MaxValorVendaEmCentavos))
		i--
		dAtA[i] = 0x28
	}
	if m.CashbackRateMicroByxPerReal != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.CashbackRateMicroByxPerReal))
		i--
		dAtA[i] = 0x20
	}
	if len(m.FaucetMaxPerTx) > 0 {
		i -= len(m.FaucetMaxPerTx)
		copy(dAtA[i:], m.FaucetMaxPerTx)
		i = encodeVarintParams(dAtA, i, uint64(len(m.FaucetMaxPerTx)))
		i--
		dAtA[i] = 0x1a
	}
	if m.FaucetEnabled {
		i--
		if m.FaucetEnabled {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x10
	}
	if len(m.FaucetAdmin) > 0 {
		i -= len(m.FaucetAdmin)
		copy(dAtA[i:], m.FaucetAdmin)
		i = encodeVarintParams(dAtA, i, uint64(len(m.FaucetAdmin)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintParams(dAtA []byte, offset int, v uint64) int {
	offset -= sovParams(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.FaucetAdmin)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	if m.FaucetEnabled {
		n += 2
	}
	l = len(m.FaucetMaxPerTx)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	if m.CashbackRateMicroByxPerReal != 0 {
		n += 1 + sovParams(uint64(m.CashbackRateMicroByxPerReal))
	}
	if m.MaxValorVendaEmCentavos != 0 {
		n += 1 + sovParams(uint64(m.MaxValorVendaEmCentavos))
	}
	if m.MaxCashbackMicroByxPorVenda != 0 {
		n += 1 + sovParams(uint64(m.MaxCashbackMicroByxPorVenda))
	}
	if m.MaxCashbackDailyPerLojaMicrobyx != 0 {
		n += 1 + sovParams(uint64(m.MaxCashbackDailyPerLojaMicrobyx))
	}
	if m.MaxSalesPerBlockPerLoja != 0 {
		n += 1 + sovParams(uint64(m.MaxSalesPerBlockPerLoja))
	}
	if m.LimitsEnabled {
		n += 2
	}
	if m.CashbackDailyRetentionDays != 0 {
		n += 1 + sovParams(uint64(m.CashbackDailyRetentionDays))
	}
	return n
}

func sovParams(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozParams(x uint64) (n int) {
	return sovParams(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FaucetAdmin", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FaucetAdmin = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field FaucetEnabled", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.FaucetEnabled = bool(v != 0)
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FaucetMaxPerTx", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FaucetMaxPerTx = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CashbackRateMicroByxPerReal", wireType)
			}
			m.CashbackRateMicroByxPerReal = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CashbackRateMicroByxPerReal |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxValorVendaEmCentavos", wireType)
			}
			m.MaxValorVendaEmCentavos = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxValorVendaEmCentavos |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxCashbackMicroByxPorVenda", wireType)
			}
			m.MaxCashbackMicroByxPorVenda = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxCashbackMicroByxPorVenda |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxCashbackDailyPerLojaMicrobyx", wireType)
			}
			m.MaxCashbackDailyPerLojaMicrobyx = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxCashbackDailyPerLojaMicrobyx |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxSalesPerBlockPerLoja", wireType)
			}
			m.MaxSalesPerBlockPerLoja = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxSalesPerBlockPerLoja |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LimitsEnabled", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.LimitsEnabled = bool(v != 0)
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CashbackDailyRetentionDays", wireType)
			}
			m.CashbackDailyRetentionDays = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CashbackDailyRetentionDays |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipParams(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowParams
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthParams
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupParams
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthParams
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthParams        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowParams          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupParams = fmt.Errorf("proto: unexpected end of group")
)
