// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: byx/payments/v1/query.proto

package types

import (
	context "context"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8d53b841170f822, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	// params holds all the parameters of this module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8d53b841170f822, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

type QueryGetPaymentRequestRequest struct {
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *QueryGetPaymentRequestRequest) Reset()         { *m = QueryGetPaymentRequestRequest{} }
func (m *QueryGetPaymentRequestRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetPaymentRequestRequest) ProtoMessage()    {}
func (*QueryGetPaymentRequestRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8d53b841170f822, []int{2}
}
func (m *QueryGetPaymentRequestRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetPaymentRequestRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetPaymentRequestRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetPaymentRequestRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetPaymentRequestRequest.Merge(m, src)
}
func (m *QueryGetPaymentRequestRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetPaymentRequestRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetPaymentRequestRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetPaymentRequestRequest proto.InternalMessageInfo

func (m *QueryGetPaymentRequestRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type QueryGetPaymentRequestResponse struct {
	PaymentRequest *PaymentRequest `protobuf:"bytes,1,opt,name=payment_request,json=paymentRequest,proto3" json:"payment_request,omitempty"`
}

func (m *QueryGetPaymentRequestResponse) Reset()         { *m = QueryGetPaymentRequestResponse{} }
func (m *QueryGetPaymentRequestResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetPaymentRequestResponse) ProtoMessage()    {}
func (*QueryGetPaymentRequestResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8d53b841170f822, []int{3}
}
func (m *QueryGetPaymentRequestResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetPaymentRequestResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetPaymentRequestResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetPaymentRequestResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetPaymentRequestResponse.Merge(m, src)
}
func (m *QueryGetPaymentRequestResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetPaymentRequestResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetPaymentRequestResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetPaymentRequestResponse proto.InternalMessageInfo

func (m *QueryGetPaymentRequestResponse) GetPaymentRequest() *PaymentRequest {
	if m != nil {
		return m.PaymentRequest
	}
	return nil
}

type QueryPaymentRequestsByLojaRequest struct {
	LojaId     uint64             `protobuf:"varint,1,opt,name=loja_id,json=lojaId,proto3" json:"loja_id,omitempty"`
	Pagination *query.PageRequest `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryPaymentRequestsByLojaRequest) Reset()         { *m = QueryPaymentRequestsByLojaRequest{} }
func (m *QueryPaymentRequestsByLojaRequest) String() string { return proto.CompactTextString(m) }
func (*QueryPaymentRequestsByLojaRequest) ProtoMessage()    {}
func (*QueryPaymentRequestsByLojaRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8d53b841170f822, []int{4}
}
func (m *QueryPaymentRequestsByLojaRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryPaymentRequestsByLojaRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryPaymentRequestsByLojaRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryPaymentRequestsByLojaRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryPaymentRequestsByLojaRequest.Merge(m, src)
}
func (m *QueryPaymentRequestsByLojaRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryPaymentRequestsByLojaRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryPaymentRequestsByLojaRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryPaymentRequestsByLojaRequest proto.InternalMessageInfo

func (m *QueryPaymentRequestsByLojaRequest) GetLojaId() uint64 {
	if m != nil {
		return m.LojaId
	}
	return 0
}

func (m *QueryPaymentRequestsByLojaRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryPaymentRequestsByLojaResponse struct {
	PaymentRequests []*PaymentRequest   `protobuf:"bytes,1,rep,name=payment_requests,json=paymentRequests,proto3" json:"payment_requests,omitempty"`
	Pagination      *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryPaymentRequestsByLojaResponse) Reset()         { *m = QueryPaymentRequestsByLojaResponse{} }
func (m *QueryPaymentRequestsByLojaResponse) String() string { return proto.CompactTextString(m) }
func (*QueryPaymentRequestsByLojaResponse) ProtoMessage()    {}
func (*QueryPaymentRequestsByLojaResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8d53b841170f822, []int{5}
}
func (m *QueryPaymentRequestsByLojaResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryPaymentRequestsByLojaResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryPaymentRequestsByLojaResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryPaymentRequestsByLojaResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryPaymentRequestsByLojaResponse.Merge(m, src)
}
func (m *QueryPaymentRequestsByLojaResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryPaymentRequestsByLojaResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryPaymentRequestsByLojaResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryPaymentRequestsByLojaResponse proto.InternalMessageInfo

func (m *QueryPaymentRequestsByLojaResponse) GetPaymentRequests() []*PaymentRequest {
	if m != nil {
		return m.PaymentRequests
	}
	return nil
}

func (m *QueryPaymentRequestsByLojaResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "byx.payments.v1.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "byx.payments.v1.QueryParamsResponse")
	proto.RegisterType((*QueryGetPaymentRequestRequest)(nil), "byx.payments.v1.QueryGetPaymentRequestRequest")
	proto.RegisterType((*QueryGetPaymentRequestResponse)(nil), "byx.payments.v1.QueryGetPaymentRequestResponse")
	proto.RegisterType((*QueryPaymentRequestsByLojaRequest)(nil), "byx.payments.v1.QueryPaymentRequestsByLojaRequest")
	proto.RegisterType((*QueryPaymentRequestsByLojaResponse)(nil), "byx.payments.v1.QueryPaymentRequestsByLojaResponse")
}

func init() { proto.RegisterFile("byx/payments/v1/query.proto", fileDescriptor_f8d53b841170f822) }

var fileDescriptor_f8d53b841170f822 = []byte{
	// 543 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x94, 0x31, 0x6f, 0xd3, 0x40,
	0x14, 0xc7, 0x73, 0x29, 0x04, 0xf1, 0x90, 0x1a, 0x38, 0x82, 0x52, 0x0c, 0x75, 0xc0, 0xa0, 0x52,
	0x75, 0xb8, 0x53, 0x12, 0xb1, 0xc0, 0x96, 0x81, 0x02, 0x62, 0x48, 0x33, 0xb2, 0x44, 0x67, 0x72,
	0xb2, 0x1c, 0x35, 0x3e, 0x37, 0xe7, 0x46, 0xb5, 0xaa, 0x2e, 0x88, 0x0f, 0x80, 0xc4, 0x27, 0x60,
	0x63, 0x64, 0x65, 0x60, 0xef, 0x58, 0x89, 0x85, 0x09, 0x41, 0x82, 0xc4, 0xd7, 0x40, 0xbe, 0x3b,
	0x97, 0x38, 0xb1, 0xdb, 0xb2, 0x24, 0xe7, 0x7b, 0xef, 0xfd, 0xdf, 0xef, 0xe5, 0xfd, 0x63, 0xb8,
	0xe3, 0xc6, 0x07, 0x34, 0x64, 0xf1, 0x88, 0x07, 0x91, 0xa4, 0x93, 0x26, 0xdd, 0xdb, 0xe7, 0xe3,
	0x98, 0x84, 0x63, 0x11, 0x09, 0x5c, 0x75, 0xe3, 0x03, 0x92, 0x06, 0xc9, 0xa4, 0x69, 0xdd, 0x60,
	0x23, 0x3f, 0x10, 0x54, 0x7d, 0xea, 0x1c, 0xab, 0xe6, 0x09, 0x4f, 0xa8, 0x23, 0x4d, 0x4e, 0xe6,
	0xf6, 0xae, 0x27, 0x84, 0xb7, 0xcb, 0x29, 0x0b, 0x7d, 0xca, 0x82, 0x40, 0x44, 0x2c, 0xf2, 0x45,
	0x20, 0x4d, 0x74, 0xeb, 0x8d, 0x90, 0x23, 0x21, 0xa9, 0xcb, 0x24, 0xd7, 0x0d, 0xe9, 0xa4, 0xe9,
	0xf2, 0x88, 0x35, 0x69, 0xc8, 0x3c, 0x3f, 0x50, 0xc9, 0xa9, 0xd2, 0x22, 0x60, 0xc8, 0xc6, 0x6c,
	0x94, 0x2a, 0xad, 0x2f, 0x47, 0xd5, 0x59, 0x87, 0x9d, 0x1a, 0xe0, 0x9d, 0x44, 0xbe, 0xab, 0x6a,
	0x7a, 0x7c, 0x6f, 0x9f, 0xcb, 0xc8, 0xd9, 0x81, 0x9b, 0x99, 0x5b, 0x19, 0x8a, 0x40, 0x72, 0xfc,
	0x04, 0x2a, 0x5a, 0x7b, 0x0d, 0xdd, 0x43, 0x9b, 0xd7, 0x5a, 0x75, 0xb2, 0x30, 0x3e, 0xd1, 0x05,
	0x9d, 0xab, 0xc7, 0x3f, 0x1a, 0xa5, 0x4f, 0x7f, 0x3e, 0x6f, 0xa1, 0x9e, 0xa9, 0x70, 0x28, 0xac,
	0x2b, 0xc9, 0x6d, 0x1e, 0x75, 0x75, 0x81, 0x69, 0x66, 0xbe, 0xf0, 0x2a, 0x94, 0xfd, 0x81, 0x12,
	0xbe, 0xd4, 0x2b, 0xfb, 0x03, 0x67, 0x08, 0x76, 0x51, 0x81, 0xc1, 0x79, 0x0e, 0x55, 0xd3, 0xbb,
	0x3f, 0xd6, 0x21, 0xc3, 0xd5, 0xc8, 0xe1, 0xca, 0x28, 0xac, 0x86, 0x99, 0x67, 0xe7, 0x1d, 0x82,
	0xfb, 0x66, 0xe0, 0xf9, 0x7b, 0xd9, 0x89, 0x5f, 0x89, 0x21, 0x4b, 0x09, 0xeb, 0x70, 0x65, 0x57,
	0x0c, 0x59, 0xff, 0x14, 0xb3, 0x92, 0x3c, 0xbe, 0x18, 0xe0, 0x67, 0x00, 0xff, 0xb6, 0xb2, 0x56,
	0x56, 0x0c, 0x1b, 0x44, 0xaf, 0x90, 0x24, 0x2b, 0x24, 0xda, 0x33, 0x66, 0x85, 0xa4, 0xcb, 0x3c,
	0x9e, 0xa2, 0xcc, 0x55, 0x3a, 0x5f, 0x10, 0x38, 0x67, 0x61, 0x98, 0xb9, 0x5f, 0xc2, 0xf5, 0x85,
	0xb9, 0x93, 0x85, 0xac, 0x5c, 0x64, 0xf0, 0x6a, 0x76, 0x70, 0x89, 0xb7, 0x73, 0xd0, 0x1f, 0x9d,
	0x8b, 0xae, 0x41, 0xe6, 0xd9, 0x5b, 0xbf, 0x56, 0xe0, 0xb2, 0x62, 0xc7, 0x11, 0x54, 0xb4, 0x0d,
	0xf0, 0x83, 0x25, 0x9c, 0x65, 0xaf, 0x59, 0x0f, 0xcf, 0x4e, 0xd2, 0xad, 0x9c, 0xc6, 0xdb, 0x6f,
	0xbf, 0x3f, 0x94, 0x6f, 0xe3, 0x3a, 0xcd, 0x77, 0x3b, 0xfe, 0x88, 0x60, 0x35, 0x3b, 0x2c, 0x26,
	0xf9, 0xca, 0x45, 0x0e, 0xb4, 0xe8, 0x85, 0xf3, 0x0d, 0x14, 0x51, 0x50, 0x9b, 0x78, 0x83, 0x16,
	0xfc, 0xc9, 0x4e, 0xf7, 0x43, 0x0f, 0xfd, 0xc1, 0x11, 0xfe, 0x8a, 0xe0, 0x56, 0xee, 0x6a, 0x71,
	0xab, 0xe8, 0x47, 0x28, 0xb6, 0xa3, 0xd5, 0xfe, 0xaf, 0x1a, 0x83, 0xfc, 0x54, 0x21, 0x3f, 0xc6,
	0xed, 0xf3, 0x91, 0xdd, 0xb8, 0x9f, 0xf8, 0x9b, 0x1e, 0x1a, 0xd3, 0x1f, 0x75, 0xc8, 0xf1, 0xd4,
	0x46, 0x27, 0x53, 0x1b, 0xfd, 0x9c, 0xda, 0xe8, 0xfd, 0xcc, 0x2e, 0x9d, 0xcc, 0xec, 0xd2, 0xf7,
	0x99, 0x5d, 0x7a, 0x5d, 0x4b, 0xd4, 0xe6, 0xf4, 0xa2, 0x38, 0xe4, 0xd2, 0xad, 0xa8, 0x77, 0x4c,
	0xfb, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xea, 0xba, 0xbf, 0xd1, 0x43, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// Retorna um pedido específico.
	PaymentRequest(ctx context.Context, in *QueryGetPaymentRequestRequest, opts ...grpc.CallOption) (*QueryGetPaymentRequestResponse, error)
	// Lista pedidos de uma loja (mais recentes primeiro).
	PaymentRequestsByLoja(ctx context.Context, in *QueryPaymentRequestsByLojaRequest, opts ...grpc.CallOption) (*QueryPaymentRequestsByLojaResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/byx.payments.v1.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) PaymentRequest(ctx context.Context, in *QueryGetPaymentRequestRequest, opts ...grpc.CallOption) (*QueryGetPaymentRequestResponse, error) {
	out := new(QueryGetPaymentRequestResponse)
	err := c.cc.Invoke(ctx, "/byx.payments.v1.Query/PaymentRequest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) PaymentRequestsByLoja(ctx context.Context, in *QueryPaymentRequestsByLojaRequest, opts ...grpc.CallOption) (*QueryPaymentRequestsByLojaResponse, error) {
	out := new(QueryPaymentRequestsByLojaResponse)
	err := c.cc.Invoke(ctx, "/byx.payments.v1.Query/PaymentRequestsByLoja", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// Retorna um pedido específico.
	PaymentRequest(context.Context, *QueryGetPaymentRequestRequest) (*QueryGetPaymentRequestResponse, error)
	// Lista pedidos de uma loja (mais recentes primeiro).
	PaymentRequestsByLoja(context.Context, *QueryPaymentRequestsByLojaRequest) (*QueryPaymentRequestsByLojaResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) PaymentRequest(ctx context.Context, req *QueryGetPaymentRequestRequest) (*QueryGetPaymentRequestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PaymentRequest not implemented")
}
func (*UnimplementedQueryServer) PaymentRequestsByLoja(ctx context.Context, req *QueryPaymentRequestsByLojaRequest) (*QueryPaymentRequestsByLojaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PaymentRequestsByLoja not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/byx.payments.v1.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_PaymentRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetPaymentRequestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).PaymentRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/byx.payments.v1.Query/PaymentRequest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).PaymentRequest(ctx, req.(*QueryGetPaymentRequestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_PaymentRequestsByLoja_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryPaymentRequestsByLojaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).PaymentRequestsByLoja(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/byx.payments.v1.Query/PaymentRequestsByLoja",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).PaymentRequestsByLoja(ctx, req.(*QueryPaymentRequestsByLojaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var Query_serviceDesc = _Query_serviceDesc
var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "byx.payments.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "PaymentRequest",
			Handler:    _Query_PaymentRequest_Handler,
		},
		{
			MethodName: "PaymentRequestsByLoja",
			Handler:    _Query_PaymentRequestsByLoja_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "byx/payments/v1/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryGetPaymentRequestRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetPaymentRequestRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetPaymentRequestRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetPaymentRequestResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetPaymentRequestResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetPaymentRequestResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.PaymentRequest != nil {
		{
			size, err := m.PaymentRequest.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryPaymentRequestsByLojaRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryPaymentRequestsByLojaRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryPaymentRequestsByLojaRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if m.LojaId != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.LojaId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryPaymentRequestsByLojaResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryPaymentRequestsByLojaResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryPaymentRequestsByLojaResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.PaymentRequests) > 0 {
		for iNdEx := len(m.PaymentRequests) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.PaymentRequests[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryGetPaymentRequestRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovQuery(uint64(m.Id))
	}
	return n
}

func (m *QueryGetPaymentRequestResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.PaymentRequest != nil {
		l = m.PaymentRequest.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryPaymentRequestsByLojaRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.LojaId != 0 {
		n += 1 + sovQuery(uint64(m.LojaId))
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryPaymentRequestsByLojaResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.PaymentRequests) > 0 {
		for _, e := range m.PaymentRequests {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetPaymentRequestRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetPaymentRequestRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetPaymentRequestRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetPaymentRequestResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetPaymentRequestResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetPaymentRequestResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PaymentRequest", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.PaymentRequest == nil {
				m.PaymentRequest = &PaymentRequest{}
			}
			if err := m.PaymentRequest.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryPaymentRequestsByLojaRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryPaymentRequestsByLojaRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryPaymentRequestsByLojaRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LojaId", wireType)
			}
			m.LojaId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LojaId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryPaymentRequestsByLojaResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryPaymentRequestsByLojaResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryPaymentRequestsByLojaResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PaymentRequests", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PaymentRequests = append(m.PaymentRequests, &PaymentRequest{})
			if err := m.PaymentRequests[len(m.PaymentRequests)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
