// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               unknown
// source: byx/certificados/v1/genesis.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Certificate, ServiceRecord } from "./certificate";
import { Params } from "./params";

export const protobufPackage = "byx.certificados.v1";

/** GenesisState defines the certificados module's genesis state. */
export interface GenesisState {
  params: Params | undefined;
  certificates: Certificate[];
  certificateCount: number;
  serviceRecords: ServiceRecord[];
  serviceCounts: ServiceCount[];
}

/** ServiceCount mantém o número de registros de serviço por certificado. */
export interface ServiceCount {
  certificateId: number;
  count: number;
}

function createBaseGenesisState(): GenesisState {
  return { params: undefined, certificates: [], certificateCount: 0, serviceRecords: [], serviceCounts: [] };
}

export const GenesisState: MessageFns<GenesisState> = {
  encode(message: GenesisState, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.params !== undefined) {
      Params.encode(message.params, writer.uint32(10).fork()).join();
    }
    for (const v of message.certificates) {
      Certificate.encode(v!, writer.uint32(18).fork()).join();
    }
    if (message.certificateCount !== 0) {
      writer.uint32(24).uint64(message.certificateCount);
    }
    for (const v of message.serviceRecords) {
      ServiceRecord.encode(v!, writer.uint32(34).fork()).join();
    }
    for (const v of message.serviceCounts) {
      ServiceCount.encode(v!, writer.uint32(42).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GenesisState {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGenesisState();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.params = Params.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.certificates.push(Certificate.decode(reader, reader.uint32()));
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.certificateCount = longToNumber(reader.uint64());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.serviceRecords.push(ServiceRecord.decode(reader, reader.uint32()));
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.serviceCounts.push(ServiceCount.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GenesisState {
    return {
      params: isSet(object.params) ? Params.fromJSON(object.params) : undefined,
      certificates: globalThis.Array.isArray(object?.certificates)
        ? object.certificates.map((e: any) => Certificate.fromJSON(e))
        : [],
      certificateCount: isSet(object.certificateCount) ? globalThis.Number(object.certificateCount) : 0,
      serviceRecords: globalThis.Array.isArray(object?.serviceRecords)
        ? object.serviceRecords.map((e: any) => ServiceRecord.fromJSON(e))
        : [],
      serviceCounts: globalThis.Array.isArray(object?.serviceCounts)
        ? object.serviceCounts.map((e: any) => ServiceCount.fromJSON(e))
        : [],
    };
  },

  toJSON(message: GenesisState): unknown {
    const obj: any = {};
    if (message.params !== undefined) {
      obj.params = Params.toJSON(message.params);
    }
    if (message.certificates?.length) {
      obj.certificates = message.certificates.map((e) => Certificate.toJSON(e));
    }
    if (message.certificateCount !== 0) {
      obj.certificateCount = Math.round(message.certificateCount);
    }
    if (message.serviceRecords?.length) {
      obj.serviceRecords = message.serviceRecords.map((e) => ServiceRecord.toJSON(e));
    }
    if (message.serviceCounts?.length) {
      obj.serviceCounts = message.serviceCounts.map((e) => ServiceCount.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GenesisState>, I>>(base?: I): GenesisState {
    return GenesisState.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GenesisState>, I>>(object: I): GenesisState {
    const message = createBaseGenesisState();
    message.params = (object.params !== undefined && object.params !== null)
      ? Params.fromPartial(object.params)
      : undefined;
    message.certificates = object.certificates?.map((e) => Certificate.fromPartial(e)) || [];
    message.certificateCount = object.certificateCount ?? 0;
    message.serviceRecords = object.serviceRecords?.map((e) => ServiceRecord.fromPartial(e)) || [];
    message.serviceCounts = object.serviceCounts?.map((e) => ServiceCount.fromPartial(e)) || [];
    return message;
  },
};

function createBaseServiceCount(): ServiceCount {
  return { certificateId: 0, count: 0 };
}

export const ServiceCount: MessageFns<ServiceCount> = {
  encode(message: ServiceCount, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.certificateId !== 0) {
      writer.uint32(8).uint64(message.certificateId);
    }
    if (message.count !== 0) {
      writer.uint32(16).uint64(message.count);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ServiceCount {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseServiceCount();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.certificateId = longToNumber(reader.uint64());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.count = longToNumber(reader.uint64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ServiceCount {
    return {
      certificateId: isSet(object.certificateId) ? globalThis.Number(object.certificateId) : 0,
      count: isSet(object.count) ? globalThis.Number(object.count) : 0,
    };
  },

  toJSON(message: ServiceCount): unknown {
    const obj: any = {};
    if (message.certificateId !== 0) {
      obj.certificateId = Math.round(message.certificateId);
    }
    if (message.count !== 0) {
      obj.count = Math.round(message.count);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ServiceCount>, I>>(base?: I): ServiceCount {
    return ServiceCount.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ServiceCount>, I>>(object: I): ServiceCount {
    const message = createBaseServiceCount();
    message.certificateId = object.certificateId ?? 0;
    message.count = object.count ?? 0;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
