// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               unknown
// source: byx/certificados/v1/query.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { PageRequest, PageResponse } from "../../../cosmos/base/query/v1beta1/pagination";
import { Certificate } from "./certificate";
import { Params } from "./params";

export const protobufPackage = "byx.certificados.v1";

export interface QueryGetCertificateRequest {
  id: number;
}

export interface QueryGetCertificateResponse {
  certificate: Certificate | undefined;
}

export interface QueryCertificatesByOwnerRequest {
  owner: string;
  pagination: PageRequest | undefined;
}

export interface QueryCertificatesByOwnerResponse {
  certificates: Certificate[];
  pagination: PageResponse | undefined;
}

export interface QueryCertificatesByMerchantRequest {
  merchantId: number;
  pagination: PageRequest | undefined;
}

export interface QueryCertificatesByMerchantResponse {
  certificates: Certificate[];
  pagination: PageResponse | undefined;
}

export interface QueryCertificatesBySerialRequest {
  serialHash: string;
  pagination: PageRequest | undefined;
}

export interface QueryCertificatesBySerialResponse {
  certificates: Certificate[];
  pagination: PageResponse | undefined;
}

export interface QueryParamsRequest {
}

export interface QueryParamsResponse {
  params: Params | undefined;
}

function createBaseQueryGetCertificateRequest(): QueryGetCertificateRequest {
  return { id: 0 };
}

export const QueryGetCertificateRequest: MessageFns<QueryGetCertificateRequest> = {
  encode(message: QueryGetCertificateRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).uint64(message.id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryGetCertificateRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryGetCertificateRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = longToNumber(reader.uint64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryGetCertificateRequest {
    return { id: isSet(object.id) ? globalThis.Number(object.id) : 0 };
  },

  toJSON(message: QueryGetCertificateRequest): unknown {
    const obj: any = {};
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryGetCertificateRequest>, I>>(base?: I): QueryGetCertificateRequest {
    return QueryGetCertificateRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryGetCertificateRequest>, I>>(object: I): QueryGetCertificateRequest {
    const message = createBaseQueryGetCertificateRequest();
    message.id = object.id ?? 0;
    return message;
  },
};

function createBaseQueryGetCertificateResponse(): QueryGetCertificateResponse {
  return { certificate: undefined };
}

export const QueryGetCertificateResponse: MessageFns<QueryGetCertificateResponse> = {
  encode(message: QueryGetCertificateResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.certificate !== undefined) {
      Certificate.encode(message.certificate, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryGetCertificateResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryGetCertificateResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.certificate = Certificate.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryGetCertificateResponse {
    return { certificate: isSet(object.certificate) ? Certificate.fromJSON(object.certificate) : undefined };
  },

  toJSON(message: QueryGetCertificateResponse): unknown {
    const obj: any = {};
    if (message.certificate !== undefined) {
      obj.certificate = Certificate.toJSON(message.certificate);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryGetCertificateResponse>, I>>(base?: I): QueryGetCertificateResponse {
    return QueryGetCertificateResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryGetCertificateResponse>, I>>(object: I): QueryGetCertificateResponse {
    const message = createBaseQueryGetCertificateResponse();
    message.certificate = (object.certificate !== undefined && object.certificate !== null)
      ? Certificate.fromPartial(object.certificate)
      : undefined;
    return message;
  },
};

function createBaseQueryCertificatesByOwnerRequest(): QueryCertificatesByOwnerRequest {
  return { owner: "", pagination: undefined };
}

export const QueryCertificatesByOwnerRequest: MessageFns<QueryCertificatesByOwnerRequest> = {
  encode(message: QueryCertificatesByOwnerRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.owner !== "") {
      writer.uint32(10).string(message.owner);
    }
    if (message.pagination !== undefined) {
      PageRequest.encode(message.pagination, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryCertificatesByOwnerRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryCertificatesByOwnerRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.owner = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.pagination = PageRequest.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryCertificatesByOwnerRequest {
    return {
      owner: isSet(object.owner) ? globalThis.String(object.owner) : "",
      pagination: isSet(object.pagination) ? PageRequest.fromJSON(object.pagination) : undefined,
    };
  },

  toJSON(message: QueryCertificatesByOwnerRequest): unknown {
    const obj: any = {};
    if (message.owner !== "") {
      obj.owner = message.owner;
    }
    if (message.pagination !== undefined) {
      obj.pagination = PageRequest.toJSON(message.pagination);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryCertificatesByOwnerRequest>, I>>(base?: I): QueryCertificatesByOwnerRequest {
    return QueryCertificatesByOwnerRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryCertificatesByOwnerRequest>, I>>(
    object: I,
  ): QueryCertificatesByOwnerRequest {
    const message = createBaseQueryCertificatesByOwnerRequest();
    message.owner = object.owner ?? "";
    message.pagination = (object.pagination !== undefined && object.pagination !== null)
      ? PageRequest.fromPartial(object.pagination)
      : undefined;
    return message;
  },
};

function createBaseQueryCertificatesByOwnerResponse(): QueryCertificatesByOwnerResponse {
  return { certificates: [], pagination: undefined };
}

export const QueryCertificatesByOwnerResponse: MessageFns<QueryCertificatesByOwnerResponse> = {
  encode(message: QueryCertificatesByOwnerResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.certificates) {
      Certificate.encode(v!, writer.uint32(10).fork()).join();
    }
    if (message.pagination !== undefined) {
      PageResponse.encode(message.pagination, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryCertificatesByOwnerResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryCertificatesByOwnerResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.certificates.push(Certificate.decode(reader, reader.uint32()));
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.pagination = PageResponse.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryCertificatesByOwnerResponse {
    return {
      certificates: globalThis.Array.isArray(object?.certificates)
        ? object.certificates.map((e: any) => Certificate.fromJSON(e))
        : [],
      pagination: isSet(object.pagination) ? PageResponse.fromJSON(object.pagination) : undefined,
    };
  },

  toJSON(message: QueryCertificatesByOwnerResponse): unknown {
    const obj: any = {};
    if (message.certificates?.length) {
      obj.certificates = message.certificates.map((e) => Certificate.toJSON(e));
    }
    if (message.pagination !== undefined) {
      obj.pagination = PageResponse.toJSON(message.pagination);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryCertificatesByOwnerResponse>, I>>(
    base?: I,
  ): QueryCertificatesByOwnerResponse {
    return QueryCertificatesByOwnerResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryCertificatesByOwnerResponse>, I>>(
    object: I,
  ): QueryCertificatesByOwnerResponse {
    const message = createBaseQueryCertificatesByOwnerResponse();
    message.certificates = object.certificates?.map((e) => Certificate.fromPartial(e)) || [];
    message.pagination = (object.pagination !== undefined && object.pagination !== null)
      ? PageResponse.fromPartial(object.pagination)
      : undefined;
    return message;
  },
};

function createBaseQueryCertificatesByMerchantRequest(): QueryCertificatesByMerchantRequest {
  return { merchantId: 0, pagination: undefined };
}

export const QueryCertificatesByMerchantRequest: MessageFns<QueryCertificatesByMerchantRequest> = {
  encode(message: QueryCertificatesByMerchantRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.merchantId !== 0) {
      writer.uint32(8).uint64(message.merchantId);
    }
    if (message.pagination !== undefined) {
      PageRequest.encode(message.pagination, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryCertificatesByMerchantRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryCertificatesByMerchantRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.merchantId = longToNumber(reader.uint64());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.pagination = PageRequest.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryCertificatesByMerchantRequest {
    return {
      merchantId: isSet(object.merchantId) ? globalThis.Number(object.merchantId) : 0,
      pagination: isSet(object.pagination) ? PageRequest.fromJSON(object.pagination) : undefined,
    };
  },

  toJSON(message: QueryCertificatesByMerchantRequest): unknown {
    const obj: any = {};
    if (message.merchantId !== 0) {
      obj.merchantId = Math.round(message.merchantId);
    }
    if (message.pagination !== undefined) {
      obj.pagination = PageRequest.toJSON(message.pagination);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryCertificatesByMerchantRequest>, I>>(
    base?: I,
  ): QueryCertificatesByMerchantRequest {
    return QueryCertificatesByMerchantRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryCertificatesByMerchantRequest>, I>>(
    object: I,
  ): QueryCertificatesByMerchantRequest {
    const message = createBaseQueryCertificatesByMerchantRequest();
    message.merchantId = object.merchantId ?? 0;
    message.pagination = (object.pagination !== undefined && object.pagination !== null)
      ? PageRequest.fromPartial(object.pagination)
      : undefined;
    return message;
  },
};

function createBaseQueryCertificatesByMerchantResponse(): QueryCertificatesByMerchantResponse {
  return { certificates: [], pagination: undefined };
}

export const QueryCertificatesByMerchantResponse: MessageFns<QueryCertificatesByMerchantResponse> = {
  encode(message: QueryCertificatesByMerchantResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.certificates) {
      Certificate.encode(v!, writer.uint32(10).fork()).join();
    }
    if (message.pagination !== undefined) {
      PageResponse.encode(message.pagination, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryCertificatesByMerchantResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryCertificatesByMerchantResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.certificates.push(Certificate.decode(reader, reader.uint32()));
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.pagination = PageResponse.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryCertificatesByMerchantResponse {
    return {
      certificates: globalThis.Array.isArray(object?.certificates)
        ? object.certificates.map((e: any) => Certificate.fromJSON(e))
        : [],
      pagination: isSet(object.pagination) ? PageResponse.fromJSON(object.pagination) : undefined,
    };
  },

  toJSON(message: QueryCertificatesByMerchantResponse): unknown {
    const obj: any = {};
    if (message.certificates?.length) {
      obj.certificates = message.certificates.map((e) => Certificate.toJSON(e));
    }
    if (message.pagination !== undefined) {
      obj.pagination = PageResponse.toJSON(message.pagination);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryCertificatesByMerchantResponse>, I>>(
    base?: I,
  ): QueryCertificatesByMerchantResponse {
    return QueryCertificatesByMerchantResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryCertificatesByMerchantResponse>, I>>(
    object: I,
  ): QueryCertificatesByMerchantResponse {
    const message = createBaseQueryCertificatesByMerchantResponse();
    message.certificates = object.certificates?.map((e) => Certificate.fromPartial(e)) || [];
    message.pagination = (object.pagination !== undefined && object.pagination !== null)
      ? PageResponse.fromPartial(object.pagination)
      : undefined;
    return message;
  },
};

function createBaseQueryCertificatesBySerialRequest(): QueryCertificatesBySerialRequest {
  return { serialHash: "", pagination: undefined };
}

export const QueryCertificatesBySerialRequest: MessageFns<QueryCertificatesBySerialRequest> = {
  encode(message: QueryCertificatesBySerialRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.serialHash !== "") {
      writer.uint32(10).string(message.serialHash);
    }
    if (message.pagination !== undefined) {
      PageRequest.encode(message.pagination, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryCertificatesBySerialRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryCertificatesBySerialRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.serialHash = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.pagination = PageRequest.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryCertificatesBySerialRequest {
    return {
      serialHash: isSet(object.serialHash) ? globalThis.String(object.serialHash) : "",
      pagination: isSet(object.pagination) ? PageRequest.fromJSON(object.pagination) : undefined,
    };
  },

  toJSON(message: QueryCertificatesBySerialRequest): unknown {
    const obj: any = {};
    if (message.serialHash !== "") {
      obj.serialHash = message.serialHash;
    }
    if (message.pagination !== undefined) {
      obj.pagination = PageRequest.toJSON(message.pagination);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryCertificatesBySerialRequest>, I>>(
    base?: I,
  ): QueryCertificatesBySerialRequest {
    return QueryCertificatesBySerialRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryCertificatesBySerialRequest>, I>>(
    object: I,
  ): QueryCertificatesBySerialRequest {
    const message = createBaseQueryCertificatesBySerialRequest();
    message.serialHash = object.serialHash ?? "";
    message.pagination = (object.pagination !== undefined && object.pagination !== null)
      ? PageRequest.fromPartial(object.pagination)
      : undefined;
    return message;
  },
};

function createBaseQueryCertificatesBySerialResponse(): QueryCertificatesBySerialResponse {
  return { certificates: [], pagination: undefined };
}

export const QueryCertificatesBySerialResponse: MessageFns<QueryCertificatesBySerialResponse> = {
  encode(message: QueryCertificatesBySerialResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.certificates) {
      Certificate.encode(v!, writer.uint32(10).fork()).join();
    }
    if (message.pagination !== undefined) {
      PageResponse.encode(message.pagination, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryCertificatesBySerialResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryCertificatesBySerialResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.certificates.push(Certificate.decode(reader, reader.uint32()));
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.pagination = PageResponse.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryCertificatesBySerialResponse {
    return {
      certificates: globalThis.Array.isArray(object?.certificates)
        ? object.certificates.map((e: any) => Certificate.fromJSON(e))
        : [],
      pagination: isSet(object.pagination) ? PageResponse.fromJSON(object.pagination) : undefined,
    };
  },

  toJSON(message: QueryCertificatesBySerialResponse): unknown {
    const obj: any = {};
    if (message.certificates?.length) {
      obj.certificates = message.certificates.map((e) => Certificate.toJSON(e));
    }
    if (message.pagination !== undefined) {
      obj.pagination = PageResponse.toJSON(message.pagination);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryCertificatesBySerialResponse>, I>>(
    base?: I,
  ): QueryCertificatesBySerialResponse {
    return QueryCertificatesBySerialResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryCertificatesBySerialResponse>, I>>(
    object: I,
  ): QueryCertificatesBySerialResponse {
    const message = createBaseQueryCertificatesBySerialResponse();
    message.certificates = object.certificates?.map((e) => Certificate.fromPartial(e)) || [];
    message.pagination = (object.pagination !== undefined && object.pagination !== null)
      ? PageResponse.fromPartial(object.pagination)
      : undefined;
    return message;
  },
};

function createBaseQueryParamsRequest(): QueryParamsRequest {
  return {};
}

export const QueryParamsRequest: MessageFns<QueryParamsRequest> = {
  encode(_: QueryParamsRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryParamsRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryParamsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): QueryParamsRequest {
    return {};
  },

  toJSON(_: QueryParamsRequest): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryParamsRequest>, I>>(base?: I): QueryParamsRequest {
    return QueryParamsRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryParamsRequest>, I>>(_: I): QueryParamsRequest {
    const message = createBaseQueryParamsRequest();
    return message;
  },
};

function createBaseQueryParamsResponse(): QueryParamsResponse {
  return { params: undefined };
}

export const QueryParamsResponse: MessageFns<QueryParamsResponse> = {
  encode(message: QueryParamsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.params !== undefined) {
      Params.encode(message.params, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryParamsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryParamsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.params = Params.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryParamsResponse {
    return { params: isSet(object.params) ? Params.fromJSON(object.params) : undefined };
  },

  toJSON(message: QueryParamsResponse): unknown {
    const obj: any = {};
    if (message.params !== undefined) {
      obj.params = Params.toJSON(message.params);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryParamsResponse>, I>>(base?: I): QueryParamsResponse {
    return QueryParamsResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryParamsResponse>, I>>(object: I): QueryParamsResponse {
    const message = createBaseQueryParamsResponse();
    message.params = (object.params !== undefined && object.params !== null)
      ? Params.fromPartial(object.params)
      : undefined;
    return message;
  },
};

/** Query defines the gRPC querier service. */
export interface Query {
  /** Certificate retorna um certificado pelo id. */
  Certificate(request: QueryGetCertificateRequest): Promise<QueryGetCertificateResponse>;
  /** CertificatesByOwner retorna certificados por owner. */
  CertificatesByOwner(request: QueryCertificatesByOwnerRequest): Promise<QueryCertificatesByOwnerResponse>;
  /** CertificatesByMerchant retorna certificados por merchant. */
  CertificatesByMerchant(request: QueryCertificatesByMerchantRequest): Promise<QueryCertificatesByMerchantResponse>;
  /** CertificatesBySerial retorna certificados associados a um serial_hash. */
  CertificatesBySerial(request: QueryCertificatesBySerialRequest): Promise<QueryCertificatesBySerialResponse>;
  /** Params retorna parâmetros do módulo. */
  Params(request: QueryParamsRequest): Promise<QueryParamsResponse>;
}

export const QueryServiceName = "byx.certificados.v1.Query";
export class QueryClientImpl implements Query {
  private readonly rpc: Rpc;
  private readonly service: string;
  constructor(rpc: Rpc, opts?: { service?: string }) {
    this.service = opts?.service || QueryServiceName;
    this.rpc = rpc;
    this.Certificate = this.Certificate.bind(this);
    this.CertificatesByOwner = this.CertificatesByOwner.bind(this);
    this.CertificatesByMerchant = this.CertificatesByMerchant.bind(this);
    this.CertificatesBySerial = this.CertificatesBySerial.bind(this);
    this.Params = this.Params.bind(this);
  }
  Certificate(request: QueryGetCertificateRequest): Promise<QueryGetCertificateResponse> {
    const data = QueryGetCertificateRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "Certificate", data);
    return promise.then((data) => QueryGetCertificateResponse.decode(new BinaryReader(data)));
  }

  CertificatesByOwner(request: QueryCertificatesByOwnerRequest): Promise<QueryCertificatesByOwnerResponse> {
    const data = QueryCertificatesByOwnerRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "CertificatesByOwner", data);
    return promise.then((data) => QueryCertificatesByOwnerResponse.decode(new BinaryReader(data)));
  }

  CertificatesByMerchant(request: QueryCertificatesByMerchantRequest): Promise<QueryCertificatesByMerchantResponse> {
    const data = QueryCertificatesByMerchantRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "CertificatesByMerchant", data);
    return promise.then((data) => QueryCertificatesByMerchantResponse.decode(new BinaryReader(data)));
  }

  CertificatesBySerial(request: QueryCertificatesBySerialRequest): Promise<QueryCertificatesBySerialResponse> {
    const data = QueryCertificatesBySerialRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "CertificatesBySerial", data);
    return promise.then((data) => QueryCertificatesBySerialResponse.decode(new BinaryReader(data)));
  }

  Params(request: QueryParamsRequest): Promise<QueryParamsResponse> {
    const data = QueryParamsRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "Params", data);
    return promise.then((data) => QueryParamsResponse.decode(new BinaryReader(data)));
  }
}

interface Rpc {
  request(service: string, method: string, data: Uint8Array): Promise<Uint8Array>;
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
