// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               unknown
// source: byx/lojas/v1/merchant.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "byx.lojas.v1";

/** Merchant defines the Merchant message. */
export interface Merchant {
  id: number;
  nome: string;
  endereco: string;
  cpfcnpj: string;
  telefone: string;
  saldo: string;
  creator: string;
}

function createBaseMerchant(): Merchant {
  return { id: 0, nome: "", endereco: "", cpfcnpj: "", telefone: "", saldo: "", creator: "" };
}

export const Merchant: MessageFns<Merchant> = {
  encode(message: Merchant, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).uint64(message.id);
    }
    if (message.nome !== "") {
      writer.uint32(18).string(message.nome);
    }
    if (message.endereco !== "") {
      writer.uint32(26).string(message.endereco);
    }
    if (message.cpfcnpj !== "") {
      writer.uint32(34).string(message.cpfcnpj);
    }
    if (message.telefone !== "") {
      writer.uint32(42).string(message.telefone);
    }
    if (message.saldo !== "") {
      writer.uint32(50).string(message.saldo);
    }
    if (message.creator !== "") {
      writer.uint32(58).string(message.creator);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Merchant {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMerchant();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = longToNumber(reader.uint64());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.nome = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.endereco = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.cpfcnpj = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.telefone = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.saldo = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.creator = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Merchant {
    return {
      id: isSet(object.id) ? globalThis.Number(object.id) : 0,
      nome: isSet(object.nome) ? globalThis.String(object.nome) : "",
      endereco: isSet(object.endereco) ? globalThis.String(object.endereco) : "",
      cpfcnpj: isSet(object.cpfcnpj) ? globalThis.String(object.cpfcnpj) : "",
      telefone: isSet(object.telefone) ? globalThis.String(object.telefone) : "",
      saldo: isSet(object.saldo) ? globalThis.String(object.saldo) : "",
      creator: isSet(object.creator) ? globalThis.String(object.creator) : "",
    };
  },

  toJSON(message: Merchant): unknown {
    const obj: any = {};
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    if (message.nome !== "") {
      obj.nome = message.nome;
    }
    if (message.endereco !== "") {
      obj.endereco = message.endereco;
    }
    if (message.cpfcnpj !== "") {
      obj.cpfcnpj = message.cpfcnpj;
    }
    if (message.telefone !== "") {
      obj.telefone = message.telefone;
    }
    if (message.saldo !== "") {
      obj.saldo = message.saldo;
    }
    if (message.creator !== "") {
      obj.creator = message.creator;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Merchant>, I>>(base?: I): Merchant {
    return Merchant.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Merchant>, I>>(object: I): Merchant {
    const message = createBaseMerchant();
    message.id = object.id ?? 0;
    message.nome = object.nome ?? "";
    message.endereco = object.endereco ?? "";
    message.cpfcnpj = object.cpfcnpj ?? "";
    message.telefone = object.telefone ?? "";
    message.saldo = object.saldo ?? "";
    message.creator = object.creator ?? "";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
