// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.7
//   protoc               unknown
// source: byx/lojas/v1/query.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { PageRequest, PageResponse } from "../../../cosmos/base/query/v1beta1/pagination";
import { Merchant } from "./merchant";
import { Params } from "./params";
import { Sale, SalesSummary } from "./sale";

export const protobufPackage = "byx.lojas.v1";

export interface QueryParamsRequest {
}

export interface QueryParamsResponse {
  /** definido em params.proto */
  params: Params | undefined;
}

export interface QueryGetMerchantRequest {
  id: number;
}

export interface QueryGetMerchantResponse {
  /** definido em merchant.proto */
  merchant: Merchant | undefined;
}

export interface QueryAllMerchantRequest {
  pagination: PageRequest | undefined;
}

export interface QueryAllMerchantResponse {
  merchant: Merchant[];
  pagination: PageResponse | undefined;
}

export interface QuerySalesByLojaRequest {
  lojaId: number;
  pagination:
    | PageRequest
    | undefined;
  /** unix seconds (inclusive) */
  startTime: number;
  /** unix seconds (inclusive) */
  endTime: number;
}

export interface QuerySalesByLojaResponse {
  sales: Sale[];
  pagination: PageResponse | undefined;
}

export interface QuerySalesSummaryRequest {
  lojaId: number;
}

export interface QuerySalesSummaryResponse {
  summary: SalesSummary | undefined;
}

function createBaseQueryParamsRequest(): QueryParamsRequest {
  return {};
}

export const QueryParamsRequest: MessageFns<QueryParamsRequest> = {
  encode(_: QueryParamsRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryParamsRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryParamsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): QueryParamsRequest {
    return {};
  },

  toJSON(_: QueryParamsRequest): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryParamsRequest>, I>>(base?: I): QueryParamsRequest {
    return QueryParamsRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryParamsRequest>, I>>(_: I): QueryParamsRequest {
    const message = createBaseQueryParamsRequest();
    return message;
  },
};

function createBaseQueryParamsResponse(): QueryParamsResponse {
  return { params: undefined };
}

export const QueryParamsResponse: MessageFns<QueryParamsResponse> = {
  encode(message: QueryParamsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.params !== undefined) {
      Params.encode(message.params, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryParamsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryParamsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.params = Params.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryParamsResponse {
    return { params: isSet(object.params) ? Params.fromJSON(object.params) : undefined };
  },

  toJSON(message: QueryParamsResponse): unknown {
    const obj: any = {};
    if (message.params !== undefined) {
      obj.params = Params.toJSON(message.params);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryParamsResponse>, I>>(base?: I): QueryParamsResponse {
    return QueryParamsResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryParamsResponse>, I>>(object: I): QueryParamsResponse {
    const message = createBaseQueryParamsResponse();
    message.params = (object.params !== undefined && object.params !== null)
      ? Params.fromPartial(object.params)
      : undefined;
    return message;
  },
};

function createBaseQueryGetMerchantRequest(): QueryGetMerchantRequest {
  return { id: 0 };
}

export const QueryGetMerchantRequest: MessageFns<QueryGetMerchantRequest> = {
  encode(message: QueryGetMerchantRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).uint64(message.id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryGetMerchantRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryGetMerchantRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = longToNumber(reader.uint64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryGetMerchantRequest {
    return { id: isSet(object.id) ? globalThis.Number(object.id) : 0 };
  },

  toJSON(message: QueryGetMerchantRequest): unknown {
    const obj: any = {};
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryGetMerchantRequest>, I>>(base?: I): QueryGetMerchantRequest {
    return QueryGetMerchantRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryGetMerchantRequest>, I>>(object: I): QueryGetMerchantRequest {
    const message = createBaseQueryGetMerchantRequest();
    message.id = object.id ?? 0;
    return message;
  },
};

function createBaseQueryGetMerchantResponse(): QueryGetMerchantResponse {
  return { merchant: undefined };
}

export const QueryGetMerchantResponse: MessageFns<QueryGetMerchantResponse> = {
  encode(message: QueryGetMerchantResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.merchant !== undefined) {
      Merchant.encode(message.merchant, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryGetMerchantResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryGetMerchantResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.merchant = Merchant.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryGetMerchantResponse {
    return { merchant: isSet(object.merchant) ? Merchant.fromJSON(object.merchant) : undefined };
  },

  toJSON(message: QueryGetMerchantResponse): unknown {
    const obj: any = {};
    if (message.merchant !== undefined) {
      obj.merchant = Merchant.toJSON(message.merchant);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryGetMerchantResponse>, I>>(base?: I): QueryGetMerchantResponse {
    return QueryGetMerchantResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryGetMerchantResponse>, I>>(object: I): QueryGetMerchantResponse {
    const message = createBaseQueryGetMerchantResponse();
    message.merchant = (object.merchant !== undefined && object.merchant !== null)
      ? Merchant.fromPartial(object.merchant)
      : undefined;
    return message;
  },
};

function createBaseQueryAllMerchantRequest(): QueryAllMerchantRequest {
  return { pagination: undefined };
}

export const QueryAllMerchantRequest: MessageFns<QueryAllMerchantRequest> = {
  encode(message: QueryAllMerchantRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.pagination !== undefined) {
      PageRequest.encode(message.pagination, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryAllMerchantRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryAllMerchantRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.pagination = PageRequest.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryAllMerchantRequest {
    return { pagination: isSet(object.pagination) ? PageRequest.fromJSON(object.pagination) : undefined };
  },

  toJSON(message: QueryAllMerchantRequest): unknown {
    const obj: any = {};
    if (message.pagination !== undefined) {
      obj.pagination = PageRequest.toJSON(message.pagination);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryAllMerchantRequest>, I>>(base?: I): QueryAllMerchantRequest {
    return QueryAllMerchantRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryAllMerchantRequest>, I>>(object: I): QueryAllMerchantRequest {
    const message = createBaseQueryAllMerchantRequest();
    message.pagination = (object.pagination !== undefined && object.pagination !== null)
      ? PageRequest.fromPartial(object.pagination)
      : undefined;
    return message;
  },
};

function createBaseQueryAllMerchantResponse(): QueryAllMerchantResponse {
  return { merchant: [], pagination: undefined };
}

export const QueryAllMerchantResponse: MessageFns<QueryAllMerchantResponse> = {
  encode(message: QueryAllMerchantResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.merchant) {
      Merchant.encode(v!, writer.uint32(10).fork()).join();
    }
    if (message.pagination !== undefined) {
      PageResponse.encode(message.pagination, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryAllMerchantResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryAllMerchantResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.merchant.push(Merchant.decode(reader, reader.uint32()));
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.pagination = PageResponse.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryAllMerchantResponse {
    return {
      merchant: globalThis.Array.isArray(object?.merchant) ? object.merchant.map((e: any) => Merchant.fromJSON(e)) : [],
      pagination: isSet(object.pagination) ? PageResponse.fromJSON(object.pagination) : undefined,
    };
  },

  toJSON(message: QueryAllMerchantResponse): unknown {
    const obj: any = {};
    if (message.merchant?.length) {
      obj.merchant = message.merchant.map((e) => Merchant.toJSON(e));
    }
    if (message.pagination !== undefined) {
      obj.pagination = PageResponse.toJSON(message.pagination);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryAllMerchantResponse>, I>>(base?: I): QueryAllMerchantResponse {
    return QueryAllMerchantResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryAllMerchantResponse>, I>>(object: I): QueryAllMerchantResponse {
    const message = createBaseQueryAllMerchantResponse();
    message.merchant = object.merchant?.map((e) => Merchant.fromPartial(e)) || [];
    message.pagination = (object.pagination !== undefined && object.pagination !== null)
      ? PageResponse.fromPartial(object.pagination)
      : undefined;
    return message;
  },
};

function createBaseQuerySalesByLojaRequest(): QuerySalesByLojaRequest {
  return { lojaId: 0, pagination: undefined, startTime: 0, endTime: 0 };
}

export const QuerySalesByLojaRequest: MessageFns<QuerySalesByLojaRequest> = {
  encode(message: QuerySalesByLojaRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.lojaId !== 0) {
      writer.uint32(8).uint64(message.lojaId);
    }
    if (message.pagination !== undefined) {
      PageRequest.encode(message.pagination, writer.uint32(18).fork()).join();
    }
    if (message.startTime !== 0) {
      writer.uint32(24).uint64(message.startTime);
    }
    if (message.endTime !== 0) {
      writer.uint32(32).uint64(message.endTime);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QuerySalesByLojaRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQuerySalesByLojaRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.lojaId = longToNumber(reader.uint64());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.pagination = PageRequest.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.startTime = longToNumber(reader.uint64());
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.endTime = longToNumber(reader.uint64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QuerySalesByLojaRequest {
    return {
      lojaId: isSet(object.lojaId)
        ? globalThis.Number(object.lojaId)
        : isSet(object.loja_id)
        ? globalThis.Number(object.loja_id)
        : 0,
      pagination: isSet(object.pagination) ? PageRequest.fromJSON(object.pagination) : undefined,
      startTime: isSet(object.startTime)
        ? globalThis.Number(object.startTime)
        : isSet(object.start_time)
        ? globalThis.Number(object.start_time)
        : 0,
      endTime: isSet(object.endTime)
        ? globalThis.Number(object.endTime)
        : isSet(object.end_time)
        ? globalThis.Number(object.end_time)
        : 0,
    };
  },

  toJSON(message: QuerySalesByLojaRequest): unknown {
    const obj: any = {};
    if (message.lojaId !== 0) {
      obj.lojaId = Math.round(message.lojaId);
    }
    if (message.pagination !== undefined) {
      obj.pagination = PageRequest.toJSON(message.pagination);
    }
    if (message.startTime !== 0) {
      obj.startTime = Math.round(message.startTime);
    }
    if (message.endTime !== 0) {
      obj.endTime = Math.round(message.endTime);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QuerySalesByLojaRequest>, I>>(base?: I): QuerySalesByLojaRequest {
    return QuerySalesByLojaRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QuerySalesByLojaRequest>, I>>(object: I): QuerySalesByLojaRequest {
    const message = createBaseQuerySalesByLojaRequest();
    message.lojaId = object.lojaId ?? 0;
    message.pagination = (object.pagination !== undefined && object.pagination !== null)
      ? PageRequest.fromPartial(object.pagination)
      : undefined;
    message.startTime = object.startTime ?? 0;
    message.endTime = object.endTime ?? 0;
    return message;
  },
};

function createBaseQuerySalesByLojaResponse(): QuerySalesByLojaResponse {
  return { sales: [], pagination: undefined };
}

export const QuerySalesByLojaResponse: MessageFns<QuerySalesByLojaResponse> = {
  encode(message: QuerySalesByLojaResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.sales) {
      Sale.encode(v!, writer.uint32(10).fork()).join();
    }
    if (message.pagination !== undefined) {
      PageResponse.encode(message.pagination, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QuerySalesByLojaResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQuerySalesByLojaResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.sales.push(Sale.decode(reader, reader.uint32()));
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.pagination = PageResponse.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QuerySalesByLojaResponse {
    return {
      sales: globalThis.Array.isArray(object?.sales) ? object.sales.map((e: any) => Sale.fromJSON(e)) : [],
      pagination: isSet(object.pagination) ? PageResponse.fromJSON(object.pagination) : undefined,
    };
  },

  toJSON(message: QuerySalesByLojaResponse): unknown {
    const obj: any = {};
    if (message.sales?.length) {
      obj.sales = message.sales.map((e) => Sale.toJSON(e));
    }
    if (message.pagination !== undefined) {
      obj.pagination = PageResponse.toJSON(message.pagination);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QuerySalesByLojaResponse>, I>>(base?: I): QuerySalesByLojaResponse {
    return QuerySalesByLojaResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QuerySalesByLojaResponse>, I>>(object: I): QuerySalesByLojaResponse {
    const message = createBaseQuerySalesByLojaResponse();
    message.sales = object.sales?.map((e) => Sale.fromPartial(e)) || [];
    message.pagination = (object.pagination !== undefined && object.pagination !== null)
      ? PageResponse.fromPartial(object.pagination)
      : undefined;
    return message;
  },
};

function createBaseQuerySalesSummaryRequest(): QuerySalesSummaryRequest {
  return { lojaId: 0 };
}

export const QuerySalesSummaryRequest: MessageFns<QuerySalesSummaryRequest> = {
  encode(message: QuerySalesSummaryRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.lojaId !== 0) {
      writer.uint32(8).uint64(message.lojaId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QuerySalesSummaryRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQuerySalesSummaryRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.lojaId = longToNumber(reader.uint64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QuerySalesSummaryRequest {
    return {
      lojaId: isSet(object.lojaId)
        ? globalThis.Number(object.lojaId)
        : isSet(object.loja_id)
        ? globalThis.Number(object.loja_id)
        : 0,
    };
  },

  toJSON(message: QuerySalesSummaryRequest): unknown {
    const obj: any = {};
    if (message.lojaId !== 0) {
      obj.lojaId = Math.round(message.lojaId);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QuerySalesSummaryRequest>, I>>(base?: I): QuerySalesSummaryRequest {
    return QuerySalesSummaryRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QuerySalesSummaryRequest>, I>>(object: I): QuerySalesSummaryRequest {
    const message = createBaseQuerySalesSummaryRequest();
    message.lojaId = object.lojaId ?? 0;
    return message;
  },
};

function createBaseQuerySalesSummaryResponse(): QuerySalesSummaryResponse {
  return { summary: undefined };
}

export const QuerySalesSummaryResponse: MessageFns<QuerySalesSummaryResponse> = {
  encode(message: QuerySalesSummaryResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.summary !== undefined) {
      SalesSummary.encode(message.summary, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QuerySalesSummaryResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQuerySalesSummaryResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.summary = SalesSummary.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QuerySalesSummaryResponse {
    return { summary: isSet(object.summary) ? SalesSummary.fromJSON(object.summary) : undefined };
  },

  toJSON(message: QuerySalesSummaryResponse): unknown {
    const obj: any = {};
    if (message.summary !== undefined) {
      obj.summary = SalesSummary.toJSON(message.summary);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QuerySalesSummaryResponse>, I>>(base?: I): QuerySalesSummaryResponse {
    return QuerySalesSummaryResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QuerySalesSummaryResponse>, I>>(object: I): QuerySalesSummaryResponse {
    const message = createBaseQuerySalesSummaryResponse();
    message.summary = (object.summary !== undefined && object.summary !== null)
      ? SalesSummary.fromPartial(object.summary)
      : undefined;
    return message;
  },
};

export interface Query {
  Params(request: QueryParamsRequest): Promise<QueryParamsResponse>;
  Merchant(request: QueryGetMerchantRequest): Promise<QueryGetMerchantResponse>;
  MerchantAll(request: QueryAllMerchantRequest): Promise<QueryAllMerchantResponse>;
  SalesByLoja(request: QuerySalesByLojaRequest): Promise<QuerySalesByLojaResponse>;
  SalesSummary(request: QuerySalesSummaryRequest): Promise<QuerySalesSummaryResponse>;
}

export const QueryServiceName = "byx.lojas.v1.Query";
export class QueryClientImpl implements Query {
  private readonly rpc: Rpc;
  private readonly service: string;
  constructor(rpc: Rpc, opts?: { service?: string }) {
    this.service = opts?.service || QueryServiceName;
    this.rpc = rpc;
    this.Params = this.Params.bind(this);
    this.Merchant = this.Merchant.bind(this);
    this.MerchantAll = this.MerchantAll.bind(this);
    this.SalesByLoja = this.SalesByLoja.bind(this);
    this.SalesSummary = this.SalesSummary.bind(this);
  }
  Params(request: QueryParamsRequest): Promise<QueryParamsResponse> {
    const data = QueryParamsRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "Params", data);
    return promise.then((data) => QueryParamsResponse.decode(new BinaryReader(data)));
  }

  Merchant(request: QueryGetMerchantRequest): Promise<QueryGetMerchantResponse> {
    const data = QueryGetMerchantRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "Merchant", data);
    return promise.then((data) => QueryGetMerchantResponse.decode(new BinaryReader(data)));
  }

  MerchantAll(request: QueryAllMerchantRequest): Promise<QueryAllMerchantResponse> {
    const data = QueryAllMerchantRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "MerchantAll", data);
    return promise.then((data) => QueryAllMerchantResponse.decode(new BinaryReader(data)));
  }

  SalesByLoja(request: QuerySalesByLojaRequest): Promise<QuerySalesByLojaResponse> {
    const data = QuerySalesByLojaRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "SalesByLoja", data);
    return promise.then((data) => QuerySalesByLojaResponse.decode(new BinaryReader(data)));
  }

  SalesSummary(request: QuerySalesSummaryRequest): Promise<QuerySalesSummaryResponse> {
    const data = QuerySalesSummaryRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "SalesSummary", data);
    return promise.then((data) => QuerySalesSummaryResponse.decode(new BinaryReader(data)));
  }
}

interface Rpc {
  request(service: string, method: string, data: Uint8Array): Promise<Uint8Array>;
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
