// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               unknown
// source: byx/lojas/v1/sale.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "byx.lojas.v1";

export interface Sale {
  id: number;
  lojaId: number;
  creator: string;
  valorEmCentavos: number;
  cliente: string;
  cashbackMicroByx: number;
  /** RFC3339 */
  timestamp: string;
  /** unix seconds (compat: optional) */
  blockTime: number;
}

export interface SalesCountState {
  lastHeight: number;
  count: number;
}

export interface SalesSummary {
  lojaId: number;
  totalVendas: number;
  totalValorEmCentavos: number;
  totalCashbackMicroByx: number;
  ticketMedioEmCentavos: number;
}

function createBaseSale(): Sale {
  return {
    id: 0,
    lojaId: 0,
    creator: "",
    valorEmCentavos: 0,
    cliente: "",
    cashbackMicroByx: 0,
    timestamp: "",
    blockTime: 0,
  };
}

export const Sale: MessageFns<Sale> = {
  encode(message: Sale, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).uint64(message.id);
    }
    if (message.lojaId !== 0) {
      writer.uint32(16).uint64(message.lojaId);
    }
    if (message.creator !== "") {
      writer.uint32(26).string(message.creator);
    }
    if (message.valorEmCentavos !== 0) {
      writer.uint32(32).uint64(message.valorEmCentavos);
    }
    if (message.cliente !== "") {
      writer.uint32(42).string(message.cliente);
    }
    if (message.cashbackMicroByx !== 0) {
      writer.uint32(48).uint64(message.cashbackMicroByx);
    }
    if (message.timestamp !== "") {
      writer.uint32(58).string(message.timestamp);
    }
    if (message.blockTime !== 0) {
      writer.uint32(64).uint64(message.blockTime);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Sale {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSale();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = longToNumber(reader.uint64());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.lojaId = longToNumber(reader.uint64());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.creator = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.valorEmCentavos = longToNumber(reader.uint64());
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.cliente = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.cashbackMicroByx = longToNumber(reader.uint64());
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.timestamp = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.blockTime = longToNumber(reader.uint64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Sale {
    return {
      id: isSet(object.id) ? globalThis.Number(object.id) : 0,
      lojaId: isSet(object.lojaId) ? globalThis.Number(object.lojaId) : 0,
      creator: isSet(object.creator) ? globalThis.String(object.creator) : "",
      valorEmCentavos: isSet(object.valorEmCentavos) ? globalThis.Number(object.valorEmCentavos) : 0,
      cliente: isSet(object.cliente) ? globalThis.String(object.cliente) : "",
      cashbackMicroByx: isSet(object.cashbackMicroByx) ? globalThis.Number(object.cashbackMicroByx) : 0,
      timestamp: isSet(object.timestamp) ? globalThis.String(object.timestamp) : "",
      blockTime: isSet(object.blockTime) ? globalThis.Number(object.blockTime) : 0,
    };
  },

  toJSON(message: Sale): unknown {
    const obj: any = {};
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    if (message.lojaId !== 0) {
      obj.lojaId = Math.round(message.lojaId);
    }
    if (message.creator !== "") {
      obj.creator = message.creator;
    }
    if (message.valorEmCentavos !== 0) {
      obj.valorEmCentavos = Math.round(message.valorEmCentavos);
    }
    if (message.cliente !== "") {
      obj.cliente = message.cliente;
    }
    if (message.cashbackMicroByx !== 0) {
      obj.cashbackMicroByx = Math.round(message.cashbackMicroByx);
    }
    if (message.timestamp !== "") {
      obj.timestamp = message.timestamp;
    }
    if (message.blockTime !== 0) {
      obj.blockTime = Math.round(message.blockTime);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Sale>, I>>(base?: I): Sale {
    return Sale.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Sale>, I>>(object: I): Sale {
    const message = createBaseSale();
    message.id = object.id ?? 0;
    message.lojaId = object.lojaId ?? 0;
    message.creator = object.creator ?? "";
    message.valorEmCentavos = object.valorEmCentavos ?? 0;
    message.cliente = object.cliente ?? "";
    message.cashbackMicroByx = object.cashbackMicroByx ?? 0;
    message.timestamp = object.timestamp ?? "";
    message.blockTime = object.blockTime ?? 0;
    return message;
  },
};

function createBaseSalesCountState(): SalesCountState {
  return { lastHeight: 0, count: 0 };
}

export const SalesCountState: MessageFns<SalesCountState> = {
  encode(message: SalesCountState, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.lastHeight !== 0) {
      writer.uint32(8).int64(message.lastHeight);
    }
    if (message.count !== 0) {
      writer.uint32(16).uint32(message.count);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SalesCountState {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSalesCountState();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.lastHeight = longToNumber(reader.int64());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.count = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SalesCountState {
    return {
      lastHeight: isSet(object.lastHeight) ? globalThis.Number(object.lastHeight) : 0,
      count: isSet(object.count) ? globalThis.Number(object.count) : 0,
    };
  },

  toJSON(message: SalesCountState): unknown {
    const obj: any = {};
    if (message.lastHeight !== 0) {
      obj.lastHeight = Math.round(message.lastHeight);
    }
    if (message.count !== 0) {
      obj.count = Math.round(message.count);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SalesCountState>, I>>(base?: I): SalesCountState {
    return SalesCountState.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SalesCountState>, I>>(object: I): SalesCountState {
    const message = createBaseSalesCountState();
    message.lastHeight = object.lastHeight ?? 0;
    message.count = object.count ?? 0;
    return message;
  },
};

function createBaseSalesSummary(): SalesSummary {
  return { lojaId: 0, totalVendas: 0, totalValorEmCentavos: 0, totalCashbackMicroByx: 0, ticketMedioEmCentavos: 0 };
}

export const SalesSummary: MessageFns<SalesSummary> = {
  encode(message: SalesSummary, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.lojaId !== 0) {
      writer.uint32(8).uint64(message.lojaId);
    }
    if (message.totalVendas !== 0) {
      writer.uint32(16).uint64(message.totalVendas);
    }
    if (message.totalValorEmCentavos !== 0) {
      writer.uint32(24).uint64(message.totalValorEmCentavos);
    }
    if (message.totalCashbackMicroByx !== 0) {
      writer.uint32(32).uint64(message.totalCashbackMicroByx);
    }
    if (message.ticketMedioEmCentavos !== 0) {
      writer.uint32(40).uint64(message.ticketMedioEmCentavos);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SalesSummary {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSalesSummary();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.lojaId = longToNumber(reader.uint64());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.totalVendas = longToNumber(reader.uint64());
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.totalValorEmCentavos = longToNumber(reader.uint64());
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.totalCashbackMicroByx = longToNumber(reader.uint64());
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.ticketMedioEmCentavos = longToNumber(reader.uint64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SalesSummary {
    return {
      lojaId: isSet(object.lojaId) ? globalThis.Number(object.lojaId) : 0,
      totalVendas: isSet(object.totalVendas) ? globalThis.Number(object.totalVendas) : 0,
      totalValorEmCentavos: isSet(object.totalValorEmCentavos) ? globalThis.Number(object.totalValorEmCentavos) : 0,
      totalCashbackMicroByx: isSet(object.totalCashbackMicroByx) ? globalThis.Number(object.totalCashbackMicroByx) : 0,
      ticketMedioEmCentavos: isSet(object.ticketMedioEmCentavos) ? globalThis.Number(object.ticketMedioEmCentavos) : 0,
    };
  },

  toJSON(message: SalesSummary): unknown {
    const obj: any = {};
    if (message.lojaId !== 0) {
      obj.lojaId = Math.round(message.lojaId);
    }
    if (message.totalVendas !== 0) {
      obj.totalVendas = Math.round(message.totalVendas);
    }
    if (message.totalValorEmCentavos !== 0) {
      obj.totalValorEmCentavos = Math.round(message.totalValorEmCentavos);
    }
    if (message.totalCashbackMicroByx !== 0) {
      obj.totalCashbackMicroByx = Math.round(message.totalCashbackMicroByx);
    }
    if (message.ticketMedioEmCentavos !== 0) {
      obj.ticketMedioEmCentavos = Math.round(message.ticketMedioEmCentavos);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SalesSummary>, I>>(base?: I): SalesSummary {
    return SalesSummary.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SalesSummary>, I>>(object: I): SalesSummary {
    const message = createBaseSalesSummary();
    message.lojaId = object.lojaId ?? 0;
    message.totalVendas = object.totalVendas ?? 0;
    message.totalValorEmCentavos = object.totalValorEmCentavos ?? 0;
    message.totalCashbackMicroByx = object.totalCashbackMicroByx ?? 0;
    message.ticketMedioEmCentavos = object.ticketMedioEmCentavos ?? 0;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
