// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: byx/payments/v1/payment.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// PaymentStatus indica o estado do pedido de pagamento.
type PaymentStatus int32

const (
	PaymentStatus_PAYMENT_STATUS_UNSPECIFIED PaymentStatus = 0
	PaymentStatus_PAYMENT_STATUS_PENDING     PaymentStatus = 1
	PaymentStatus_PAYMENT_STATUS_PAID        PaymentStatus = 2
	PaymentStatus_PAYMENT_STATUS_EXPIRED     PaymentStatus = 3
	PaymentStatus_PAYMENT_STATUS_CANCELED    PaymentStatus = 4
)

var PaymentStatus_name = map[int32]string{
	0: "PAYMENT_STATUS_UNSPECIFIED",
	1: "PAYMENT_STATUS_PENDING",
	2: "PAYMENT_STATUS_PAID",
	3: "PAYMENT_STATUS_EXPIRED",
	4: "PAYMENT_STATUS_CANCELED",
}

var PaymentStatus_value = map[string]int32{
	"PAYMENT_STATUS_UNSPECIFIED": 0,
	"PAYMENT_STATUS_PENDING":     1,
	"PAYMENT_STATUS_PAID":        2,
	"PAYMENT_STATUS_EXPIRED":     3,
	"PAYMENT_STATUS_CANCELED":    4,
}

func (x PaymentStatus) String() string {
	return proto.EnumName(PaymentStatus_name, int32(x))
}

func (PaymentStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_5b242da0449b1059, []int{0}
}

// PaymentRequest representa um pedido de pagamento criado por uma loja.
type PaymentRequest struct {
	Id             uint64        `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	LojaId         uint64        `protobuf:"varint,2,opt,name=loja_id,json=lojaId,proto3" json:"loja_id,omitempty"`
	AmountMicrobyx uint64        `protobuf:"varint,3,opt,name=amount_microbyx,json=amountMicrobyx,proto3" json:"amount_microbyx,omitempty"`
	Memo           string        `protobuf:"bytes,4,opt,name=memo,proto3" json:"memo,omitempty"`
	Status         PaymentStatus `protobuf:"varint,5,opt,name=status,proto3,enum=byx.payments.v1.PaymentStatus" json:"status,omitempty"`
	CreatedAtUnix  uint64        `protobuf:"varint,6,opt,name=created_at_unix,json=createdAtUnix,proto3" json:"created_at_unix,omitempty"`
	ExpiresAtUnix  uint64        `protobuf:"varint,7,opt,name=expires_at_unix,json=expiresAtUnix,proto3" json:"expires_at_unix,omitempty"`
	Payer          string        `protobuf:"bytes,8,opt,name=payer,proto3" json:"payer,omitempty"`
	PaidAtUnix     uint64        `protobuf:"varint,9,opt,name=paid_at_unix,json=paidAtUnix,proto3" json:"paid_at_unix,omitempty"`
}

func (m *PaymentRequest) Reset()         { *m = PaymentRequest{} }
func (m *PaymentRequest) String() string { return proto.CompactTextString(m) }
func (*PaymentRequest) ProtoMessage()    {}
func (*PaymentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5b242da0449b1059, []int{0}
}
func (m *PaymentRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PaymentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PaymentRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *PaymentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PaymentRequest.Merge(m, src)
}
func (m *PaymentRequest) XXX_Size() int {
	return m.Size()
}
func (m *PaymentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PaymentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PaymentRequest proto.InternalMessageInfo

func (m *PaymentRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *PaymentRequest) GetLojaId() uint64 {
	if m != nil {
		return m.LojaId
	}
	return 0
}

func (m *PaymentRequest) GetAmountMicrobyx() uint64 {
	if m != nil {
		return m.AmountMicrobyx
	}
	return 0
}

func (m *PaymentRequest) GetMemo() string {
	if m != nil {
		return m.Memo
	}
	return ""
}

func (m *PaymentRequest) GetStatus() PaymentStatus {
	if m != nil {
		return m.Status
	}
	return PaymentStatus_PAYMENT_STATUS_UNSPECIFIED
}

func (m *PaymentRequest) GetCreatedAtUnix() uint64 {
	if m != nil {
		return m.CreatedAtUnix
	}
	return 0
}

func (m *PaymentRequest) GetExpiresAtUnix() uint64 {
	if m != nil {
		return m.ExpiresAtUnix
	}
	return 0
}

func (m *PaymentRequest) GetPayer() string {
	if m != nil {
		return m.Payer
	}
	return ""
}

func (m *PaymentRequest) GetPaidAtUnix() uint64 {
	if m != nil {
		return m.PaidAtUnix
	}
	return 0
}

func init() {
	proto.RegisterEnum("byx.payments.v1.PaymentStatus", PaymentStatus_name, PaymentStatus_value)
	proto.RegisterType((*PaymentRequest)(nil), "byx.payments.v1.PaymentRequest")
}

func init() { proto.RegisterFile("byx/payments/v1/payment.proto", fileDescriptor_5b242da0449b1059) }

var fileDescriptor_5b242da0449b1059 = []byte{
	// 440 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x92, 0xdf, 0x8a, 0xd3, 0x40,
	0x14, 0x87, 0x3b, 0xd9, 0x6e, 0xd7, 0x3d, 0xb8, 0x6d, 0x18, 0x8b, 0x8d, 0x15, 0x43, 0xf1, 0x42,
	0x8b, 0x60, 0xca, 0x2a, 0x78, 0x9f, 0x6d, 0xa2, 0x04, 0xdc, 0x10, 0x92, 0x16, 0xd4, 0x9b, 0x90,
	0x36, 0x43, 0x19, 0x31, 0x99, 0x98, 0x99, 0x2e, 0xc9, 0x5b, 0xf8, 0x02, 0xbe, 0x85, 0x0f, 0xe1,
	0x65, 0xf1, 0xca, 0x4b, 0x69, 0x5f, 0x44, 0x92, 0x49, 0xfd, 0x13, 0xf6, 0xee, 0xcc, 0xef, 0xfb,
	0x72, 0xe6, 0x64, 0x38, 0xf0, 0x68, 0x55, 0x16, 0xb3, 0x2c, 0x2a, 0x13, 0x92, 0x0a, 0x3e, 0xbb,
	0xb9, 0x3c, 0xd6, 0x46, 0x96, 0x33, 0xc1, 0xf0, 0x60, 0x55, 0x16, 0xc6, 0x11, 0x1b, 0x37, 0x97,
	0xe3, 0xe1, 0x86, 0x6d, 0x58, 0xcd, 0x66, 0x55, 0x25, 0xb5, 0xf1, 0x83, 0x35, 0xe3, 0x09, 0xe3,
	0xa1, 0x04, 0xf2, 0x20, 0xd1, 0xe3, 0x9d, 0x02, 0x7d, 0x4f, 0x36, 0xf0, 0xc9, 0xe7, 0x2d, 0xe1,
	0x02, 0xf7, 0x41, 0xa1, 0xb1, 0x86, 0x26, 0x68, 0xda, 0xf5, 0x15, 0x1a, 0xe3, 0x11, 0x9c, 0x7d,
	0x62, 0x1f, 0xa3, 0x90, 0xc6, 0x9a, 0x52, 0x87, 0xbd, 0xea, 0xe8, 0xc4, 0xf8, 0x29, 0x0c, 0xa2,
	0x84, 0x6d, 0x53, 0x11, 0x26, 0x74, 0x9d, 0xb3, 0x55, 0x59, 0x68, 0x27, 0xb5, 0xd0, 0x97, 0xf1,
	0x75, 0x93, 0x62, 0x0c, 0xdd, 0x84, 0x24, 0x4c, 0xeb, 0x4e, 0xd0, 0xf4, 0xdc, 0xaf, 0x6b, 0xfc,
	0x0a, 0x7a, 0x5c, 0x44, 0x62, 0xcb, 0xb5, 0xd3, 0x09, 0x9a, 0xf6, 0x5f, 0xe8, 0x46, 0xeb, 0x5f,
	0x8c, 0x66, 0xac, 0xa0, 0xb6, 0xfc, 0xc6, 0xc6, 0x4f, 0x60, 0xb0, 0xce, 0x49, 0x24, 0x48, 0x1c,
	0x46, 0x22, 0xdc, 0xa6, 0xb4, 0xd0, 0x7a, 0xf5, 0xa5, 0x17, 0x4d, 0x6c, 0x8a, 0x65, 0x4a, 0x8b,
	0xca, 0x23, 0x45, 0x46, 0x73, 0xc2, 0xff, 0x78, 0x67, 0xd2, 0x6b, 0xe2, 0xc6, 0x33, 0xe0, 0x34,
	0x8b, 0x4a, 0x92, 0x6b, 0x77, 0xaa, 0xe1, 0xae, 0xb4, 0x1f, 0xdf, 0x9e, 0x0f, 0x9b, 0x17, 0x32,
	0xe3, 0x38, 0x27, 0x9c, 0x07, 0x22, 0xa7, 0xe9, 0xc6, 0x97, 0x1a, 0x9e, 0xc0, 0xdd, 0x2c, 0xa2,
	0x7f, 0x2f, 0x3f, 0xaf, 0x9b, 0x42, 0x95, 0xc9, 0x8e, 0xcf, 0xbe, 0x22, 0xb8, 0xf8, 0x6f, 0x76,
	0xac, 0xc3, 0xd8, 0x33, 0xdf, 0x5f, 0xdb, 0xee, 0x22, 0x0c, 0x16, 0xe6, 0x62, 0x19, 0x84, 0x4b,
	0x37, 0xf0, 0xec, 0xb9, 0xf3, 0xda, 0xb1, 0x2d, 0xb5, 0x83, 0xc7, 0x70, 0xbf, 0xc5, 0x3d, 0xdb,
	0xb5, 0x1c, 0xf7, 0x8d, 0x8a, 0xf0, 0x08, 0xee, 0xb5, 0x99, 0xe9, 0x58, 0xaa, 0x72, 0xcb, 0x47,
	0xf6, 0x3b, 0xcf, 0xf1, 0x6d, 0x4b, 0x3d, 0xc1, 0x0f, 0x61, 0xd4, 0x62, 0x73, 0xd3, 0x9d, 0xdb,
	0x6f, 0x6d, 0x4b, 0xed, 0x5e, 0x19, 0xdf, 0xf7, 0x3a, 0xda, 0xed, 0x75, 0xf4, 0x6b, 0xaf, 0xa3,
	0x2f, 0x07, 0xbd, 0xb3, 0x3b, 0xe8, 0x9d, 0x9f, 0x07, 0xbd, 0xf3, 0x61, 0x58, 0x6d, 0xdb, 0x3f,
	0xfb, 0x26, 0xca, 0x8c, 0xf0, 0x55, 0xaf, 0xde, 0x94, 0x97, 0xbf, 0x03, 0x00, 0x00, 0xff, 0xff,
	0x6b, 0xe8, 0x76, 0x5e, 0x8c, 0x02, 0x00, 0x00,
}

func (m *PaymentRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PaymentRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PaymentRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.PaidAtUnix != 0 {
		i = encodeVarintPayment(dAtA, i, uint64(m.PaidAtUnix))
		i--
		dAtA[i] = 0x48
	}
	if len(m.Payer) > 0 {
		i -= len(m.Payer)
		copy(dAtA[i:], m.Payer)
		i = encodeVarintPayment(dAtA, i, uint64(len(m.Payer)))
		i--
		dAtA[i] = 0x42
	}
	if m.ExpiresAtUnix != 0 {
		i = encodeVarintPayment(dAtA, i, uint64(m.ExpiresAtUnix))
		i--
		dAtA[i] = 0x38
	}
	if m.CreatedAtUnix != 0 {
		i = encodeVarintPayment(dAtA, i, uint64(m.CreatedAtUnix))
		i--
		dAtA[i] = 0x30
	}
	if m.Status != 0 {
		i = encodeVarintPayment(dAtA, i, uint64(m.Status))
		i--
		dAtA[i] = 0x28
	}
	if len(m.Memo) > 0 {
		i -= len(m.Memo)
		copy(dAtA[i:], m.Memo)
		i = encodeVarintPayment(dAtA, i, uint64(len(m.Memo)))
		i--
		dAtA[i] = 0x22
	}
	if m.AmountMicrobyx != 0 {
		i = encodeVarintPayment(dAtA, i, uint64(m.AmountMicrobyx))
		i--
		dAtA[i] = 0x18
	}
	if m.LojaId != 0 {
		i = encodeVarintPayment(dAtA, i, uint64(m.LojaId))
		i--
		dAtA[i] = 0x10
	}
	if m.Id != 0 {
		i = encodeVarintPayment(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintPayment(dAtA []byte, offset int, v uint64) int {
	offset -= sovPayment(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *PaymentRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovPayment(uint64(m.Id))
	}
	if m.LojaId != 0 {
		n += 1 + sovPayment(uint64(m.LojaId))
	}
	if m.AmountMicrobyx != 0 {
		n += 1 + sovPayment(uint64(m.AmountMicrobyx))
	}
	l = len(m.Memo)
	if l > 0 {
		n += 1 + l + sovPayment(uint64(l))
	}
	if m.Status != 0 {
		n += 1 + sovPayment(uint64(m.Status))
	}
	if m.CreatedAtUnix != 0 {
		n += 1 + sovPayment(uint64(m.CreatedAtUnix))
	}
	if m.ExpiresAtUnix != 0 {
		n += 1 + sovPayment(uint64(m.ExpiresAtUnix))
	}
	l = len(m.Payer)
	if l > 0 {
		n += 1 + l + sovPayment(uint64(l))
	}
	if m.PaidAtUnix != 0 {
		n += 1 + sovPayment(uint64(m.PaidAtUnix))
	}
	return n
}

func sovPayment(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozPayment(x uint64) (n int) {
	return sovPayment(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *PaymentRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPayment
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PaymentRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PaymentRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPayment
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LojaId", wireType)
			}
			m.LojaId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPayment
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LojaId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AmountMicrobyx", wireType)
			}
			m.AmountMicrobyx = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPayment
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AmountMicrobyx |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Memo", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPayment
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPayment
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPayment
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Memo = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPayment
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= PaymentStatus(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatedAtUnix", wireType)
			}
			m.CreatedAtUnix = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPayment
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CreatedAtUnix |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExpiresAtUnix", wireType)
			}
			m.ExpiresAtUnix = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPayment
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ExpiresAtUnix |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Payer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPayment
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPayment
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPayment
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Payer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PaidAtUnix", wireType)
			}
			m.PaidAtUnix = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPayment
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PaidAtUnix |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipPayment(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPayment
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipPayment(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowPayment
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPayment
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPayment
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthPayment
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupPayment
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthPayment
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthPayment        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowPayment          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupPayment = fmt.Errorf("proto: unexpected end of group")
)
