// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: byx/payments/v1/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// MsgUpdateParams is the Msg/UpdateParams request type.
type MsgUpdateParams struct {
	// authority is the address that controls the module (defaults to x/gov unless overwritten).
	Authority string `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	// params defines the module parameters to update.
	//
	// NOTE: All parameters must be supplied.
	Params Params `protobuf:"bytes,2,opt,name=params,proto3" json:"params"`
}

func (m *MsgUpdateParams) Reset()         { *m = MsgUpdateParams{} }
func (m *MsgUpdateParams) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateParams) ProtoMessage()    {}
func (*MsgUpdateParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_dfd66c0d629e422e, []int{0}
}
func (m *MsgUpdateParams) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateParams.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateParams.Merge(m, src)
}
func (m *MsgUpdateParams) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateParams) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateParams.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateParams proto.InternalMessageInfo

func (m *MsgUpdateParams) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func (m *MsgUpdateParams) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

// MsgUpdateParamsResponse defines the response structure for executing a
// MsgUpdateParams message.
type MsgUpdateParamsResponse struct {
}

func (m *MsgUpdateParamsResponse) Reset()         { *m = MsgUpdateParamsResponse{} }
func (m *MsgUpdateParamsResponse) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateParamsResponse) ProtoMessage()    {}
func (*MsgUpdateParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dfd66c0d629e422e, []int{1}
}
func (m *MsgUpdateParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateParamsResponse.Merge(m, src)
}
func (m *MsgUpdateParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateParamsResponse proto.InternalMessageInfo

// MsgCreatePaymentRequest cria um pedido de pagamento para uma loja.
type MsgCreatePaymentRequest struct {
	Creator          string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	LojaId           uint64 `protobuf:"varint,2,opt,name=loja_id,json=lojaId,proto3" json:"loja_id,omitempty"`
	AmountMicrobyx   uint64 `protobuf:"varint,3,opt,name=amount_microbyx,json=amountMicrobyx,proto3" json:"amount_microbyx,omitempty"`
	Memo             string `protobuf:"bytes,4,opt,name=memo,proto3" json:"memo,omitempty"`
	ExpiresInSeconds uint64 `protobuf:"varint,5,opt,name=expires_in_seconds,json=expiresInSeconds,proto3" json:"expires_in_seconds,omitempty"`
}

func (m *MsgCreatePaymentRequest) Reset()         { *m = MsgCreatePaymentRequest{} }
func (m *MsgCreatePaymentRequest) String() string { return proto.CompactTextString(m) }
func (*MsgCreatePaymentRequest) ProtoMessage()    {}
func (*MsgCreatePaymentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dfd66c0d629e422e, []int{2}
}
func (m *MsgCreatePaymentRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreatePaymentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreatePaymentRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreatePaymentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreatePaymentRequest.Merge(m, src)
}
func (m *MsgCreatePaymentRequest) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreatePaymentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreatePaymentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreatePaymentRequest proto.InternalMessageInfo

func (m *MsgCreatePaymentRequest) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgCreatePaymentRequest) GetLojaId() uint64 {
	if m != nil {
		return m.LojaId
	}
	return 0
}

func (m *MsgCreatePaymentRequest) GetAmountMicrobyx() uint64 {
	if m != nil {
		return m.AmountMicrobyx
	}
	return 0
}

func (m *MsgCreatePaymentRequest) GetMemo() string {
	if m != nil {
		return m.Memo
	}
	return ""
}

func (m *MsgCreatePaymentRequest) GetExpiresInSeconds() uint64 {
	if m != nil {
		return m.ExpiresInSeconds
	}
	return 0
}

type MsgCreatePaymentRequestResponse struct {
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *MsgCreatePaymentRequestResponse) Reset()         { *m = MsgCreatePaymentRequestResponse{} }
func (m *MsgCreatePaymentRequestResponse) String() string { return proto.CompactTextString(m) }
func (*MsgCreatePaymentRequestResponse) ProtoMessage()    {}
func (*MsgCreatePaymentRequestResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dfd66c0d629e422e, []int{3}
}
func (m *MsgCreatePaymentRequestResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreatePaymentRequestResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreatePaymentRequestResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreatePaymentRequestResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreatePaymentRequestResponse.Merge(m, src)
}
func (m *MsgCreatePaymentRequestResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreatePaymentRequestResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreatePaymentRequestResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreatePaymentRequestResponse proto.InternalMessageInfo

func (m *MsgCreatePaymentRequestResponse) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

// MsgPayPaymentRequest permite um pagador liquidar um pedido pendente.
type MsgPayPaymentRequest struct {
	Creator   string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	RequestId uint64 `protobuf:"varint,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
}

func (m *MsgPayPaymentRequest) Reset()         { *m = MsgPayPaymentRequest{} }
func (m *MsgPayPaymentRequest) String() string { return proto.CompactTextString(m) }
func (*MsgPayPaymentRequest) ProtoMessage()    {}
func (*MsgPayPaymentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dfd66c0d629e422e, []int{4}
}
func (m *MsgPayPaymentRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgPayPaymentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgPayPaymentRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgPayPaymentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgPayPaymentRequest.Merge(m, src)
}
func (m *MsgPayPaymentRequest) XXX_Size() int {
	return m.Size()
}
func (m *MsgPayPaymentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgPayPaymentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MsgPayPaymentRequest proto.InternalMessageInfo

func (m *MsgPayPaymentRequest) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgPayPaymentRequest) GetRequestId() uint64 {
	if m != nil {
		return m.RequestId
	}
	return 0
}

type MsgPayPaymentRequestResponse struct {
	PaymentRequest *PaymentRequest `protobuf:"bytes,1,opt,name=payment_request,json=paymentRequest,proto3" json:"payment_request,omitempty"`
}

func (m *MsgPayPaymentRequestResponse) Reset()         { *m = MsgPayPaymentRequestResponse{} }
func (m *MsgPayPaymentRequestResponse) String() string { return proto.CompactTextString(m) }
func (*MsgPayPaymentRequestResponse) ProtoMessage()    {}
func (*MsgPayPaymentRequestResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dfd66c0d629e422e, []int{5}
}
func (m *MsgPayPaymentRequestResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgPayPaymentRequestResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgPayPaymentRequestResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgPayPaymentRequestResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgPayPaymentRequestResponse.Merge(m, src)
}
func (m *MsgPayPaymentRequestResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgPayPaymentRequestResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgPayPaymentRequestResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgPayPaymentRequestResponse proto.InternalMessageInfo

func (m *MsgPayPaymentRequestResponse) GetPaymentRequest() *PaymentRequest {
	if m != nil {
		return m.PaymentRequest
	}
	return nil
}

// MsgPayWithCertificate paga um pedido e transfere um certificado do payer para o merchant owner.
type MsgPayWithCertificate struct {
	// request_id é o id numérico do pedido em formato string (para payload de QR).
	RequestId     string `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	CertificateId uint64 `protobuf:"varint,2,opt,name=certificate_id,json=certificateId,proto3" json:"certificate_id,omitempty"`
	Payer         string `protobuf:"bytes,3,opt,name=payer,proto3" json:"payer,omitempty"`
}

func (m *MsgPayWithCertificate) Reset()         { *m = MsgPayWithCertificate{} }
func (m *MsgPayWithCertificate) String() string { return proto.CompactTextString(m) }
func (*MsgPayWithCertificate) ProtoMessage()    {}
func (*MsgPayWithCertificate) Descriptor() ([]byte, []int) {
	return fileDescriptor_dfd66c0d629e422e, []int{6}
}
func (m *MsgPayWithCertificate) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgPayWithCertificate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgPayWithCertificate.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgPayWithCertificate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgPayWithCertificate.Merge(m, src)
}
func (m *MsgPayWithCertificate) XXX_Size() int {
	return m.Size()
}
func (m *MsgPayWithCertificate) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgPayWithCertificate.DiscardUnknown(m)
}

var xxx_messageInfo_MsgPayWithCertificate proto.InternalMessageInfo

func (m *MsgPayWithCertificate) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

func (m *MsgPayWithCertificate) GetCertificateId() uint64 {
	if m != nil {
		return m.CertificateId
	}
	return 0
}

func (m *MsgPayWithCertificate) GetPayer() string {
	if m != nil {
		return m.Payer
	}
	return ""
}

type MsgPayWithCertificateResponse struct {
	PaymentRequest *PaymentRequest `protobuf:"bytes,1,opt,name=payment_request,json=paymentRequest,proto3" json:"payment_request,omitempty"`
}

func (m *MsgPayWithCertificateResponse) Reset()         { *m = MsgPayWithCertificateResponse{} }
func (m *MsgPayWithCertificateResponse) String() string { return proto.CompactTextString(m) }
func (*MsgPayWithCertificateResponse) ProtoMessage()    {}
func (*MsgPayWithCertificateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dfd66c0d629e422e, []int{7}
}
func (m *MsgPayWithCertificateResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgPayWithCertificateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgPayWithCertificateResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgPayWithCertificateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgPayWithCertificateResponse.Merge(m, src)
}
func (m *MsgPayWithCertificateResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgPayWithCertificateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgPayWithCertificateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgPayWithCertificateResponse proto.InternalMessageInfo

func (m *MsgPayWithCertificateResponse) GetPaymentRequest() *PaymentRequest {
	if m != nil {
		return m.PaymentRequest
	}
	return nil
}

func init() {
	proto.RegisterType((*MsgUpdateParams)(nil), "byx.payments.v1.MsgUpdateParams")
	proto.RegisterType((*MsgUpdateParamsResponse)(nil), "byx.payments.v1.MsgUpdateParamsResponse")
	proto.RegisterType((*MsgCreatePaymentRequest)(nil), "byx.payments.v1.MsgCreatePaymentRequest")
	proto.RegisterType((*MsgCreatePaymentRequestResponse)(nil), "byx.payments.v1.MsgCreatePaymentRequestResponse")
	proto.RegisterType((*MsgPayPaymentRequest)(nil), "byx.payments.v1.MsgPayPaymentRequest")
	proto.RegisterType((*MsgPayPaymentRequestResponse)(nil), "byx.payments.v1.MsgPayPaymentRequestResponse")
	proto.RegisterType((*MsgPayWithCertificate)(nil), "byx.payments.v1.MsgPayWithCertificate")
	proto.RegisterType((*MsgPayWithCertificateResponse)(nil), "byx.payments.v1.MsgPayWithCertificateResponse")
}

func init() { proto.RegisterFile("byx/payments/v1/tx.proto", fileDescriptor_dfd66c0d629e422e) }

var fileDescriptor_dfd66c0d629e422e = []byte{
	// 759 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x55, 0xcd, 0x6b, 0x13, 0x4f,
	0x18, 0xce, 0xa6, 0x69, 0x4b, 0xa6, 0xbf, 0x5f, 0x62, 0x87, 0x48, 0xd2, 0xd0, 0xa6, 0xed, 0x62,
	0x6b, 0x09, 0xed, 0xae, 0x89, 0xa8, 0x10, 0xf0, 0x60, 0x7b, 0x69, 0x0e, 0x91, 0x92, 0x22, 0x42,
	0x2f, 0xcb, 0x26, 0x3b, 0x6e, 0x46, 0xba, 0x3b, 0xeb, 0xce, 0xb4, 0x66, 0x11, 0x41, 0x7a, 0x12,
	0x4f, 0x82, 0x67, 0xc1, 0x63, 0x8f, 0x3d, 0x78, 0xf0, 0xe0, 0xc1, 0x63, 0x8f, 0x45, 0x2f, 0x9e,
	0x44, 0x5a, 0xa1, 0x7f, 0x81, 0x77, 0xd9, 0x99, 0xcd, 0xd7, 0x66, 0x63, 0x2b, 0xf4, 0x12, 0x66,
	0xdf, 0xe7, 0x79, 0xdf, 0xf7, 0x79, 0x9f, 0xcc, 0x07, 0xc8, 0x35, 0xbc, 0xb6, 0xea, 0xe8, 0x9e,
	0x85, 0x6c, 0x46, 0xd5, 0xfd, 0x92, 0xca, 0xda, 0x8a, 0xe3, 0x12, 0x46, 0x60, 0xba, 0xe1, 0xb5,
	0x95, 0x0e, 0xa2, 0xec, 0x97, 0xf2, 0xd3, 0xba, 0x85, 0x6d, 0xa2, 0xf2, 0x5f, 0xc1, 0xc9, 0x67,
	0x9b, 0x84, 0x5a, 0x84, 0xaa, 0x16, 0x35, 0xfd, 0x5c, 0x8b, 0x9a, 0x01, 0x30, 0x23, 0x00, 0x8d,
	0x7f, 0xa9, 0xe2, 0x23, 0x80, 0x32, 0x26, 0x31, 0x89, 0x88, 0xfb, 0xab, 0x20, 0x3a, 0x6b, 0x12,
	0x62, 0xee, 0x22, 0x55, 0x77, 0xb0, 0xaa, 0xdb, 0x36, 0x61, 0x3a, 0xc3, 0xc4, 0xee, 0xe4, 0xcc,
	0x86, 0x55, 0x3a, 0xba, 0xab, 0x5b, 0x1d, 0x74, 0x6e, 0x18, 0xe5, 0x6b, 0x01, 0xcb, 0x9f, 0x24,
	0x90, 0xae, 0x51, 0xf3, 0x91, 0x63, 0xe8, 0x0c, 0x6d, 0xf1, 0x44, 0x78, 0x17, 0x24, 0xf5, 0x3d,
	0xd6, 0x22, 0x2e, 0x66, 0x5e, 0x4e, 0x5a, 0x90, 0x56, 0x92, 0xeb, 0xb9, 0xaf, 0x1f, 0xd7, 0x32,
	0x81, 0xd2, 0x07, 0x86, 0xe1, 0x22, 0x4a, 0xb7, 0x99, 0x8b, 0x6d, 0xb3, 0xde, 0xa3, 0xc2, 0x0a,
	0x98, 0x10, 0xad, 0x73, 0xf1, 0x05, 0x69, 0x65, 0xaa, 0x9c, 0x55, 0x42, 0x2e, 0x29, 0xa2, 0xc1,
	0x7a, 0xf2, 0xf8, 0xc7, 0x7c, 0xec, 0xf0, 0xfc, 0xa8, 0x28, 0xd5, 0x83, 0x8c, 0x4a, 0xe9, 0xe0,
	0xfc, 0xa8, 0xd8, 0xab, 0xf5, 0xe6, 0xfc, 0xa8, 0x58, 0xf0, 0x95, 0xf7, 0x69, 0x0f, 0xc9, 0x94,
	0x67, 0x40, 0x36, 0x14, 0xaa, 0x23, 0xea, 0x10, 0x9b, 0x22, 0xf9, 0x75, 0x9c, 0x63, 0x1b, 0x2e,
	0xe2, 0x18, 0x2f, 0x50, 0x47, 0xcf, 0xf6, 0x10, 0x65, 0xb0, 0x0c, 0x26, 0x9b, 0x7e, 0x9c, 0xb8,
	0x17, 0xce, 0xd6, 0x21, 0xc2, 0x2c, 0x98, 0xdc, 0x25, 0x4f, 0x75, 0x0d, 0x1b, 0x7c, 0xb4, 0x44,
	0x7d, 0xc2, 0xff, 0xac, 0x1a, 0xf0, 0x26, 0x48, 0xeb, 0x16, 0xd9, 0xb3, 0x99, 0x66, 0xe1, 0xa6,
	0x4b, 0x1a, 0x5e, 0x3b, 0x37, 0xc6, 0x09, 0x29, 0x11, 0xae, 0x05, 0x51, 0x08, 0x41, 0xc2, 0x42,
	0x16, 0xc9, 0x25, 0xfc, 0x96, 0x75, 0xbe, 0x86, 0xab, 0x00, 0xa2, 0xb6, 0x83, 0x5d, 0x44, 0x35,
	0x6c, 0x6b, 0x14, 0x35, 0x89, 0x6d, 0xd0, 0xdc, 0x38, 0xcf, 0xbf, 0x16, 0x20, 0x55, 0x7b, 0x5b,
	0xc4, 0x2b, 0x77, 0x7c, 0x87, 0x3a, 0x8a, 0x7c, 0x7f, 0x6e, 0x0c, 0xfc, 0xb3, 0x23, 0xc6, 0x95,
	0x4b, 0x60, 0x7e, 0x04, 0xd4, 0x71, 0x0b, 0xa6, 0x40, 0x1c, 0x1b, 0xdc, 0x8c, 0x44, 0x3d, 0x8e,
	0x0d, 0xf9, 0xbd, 0x04, 0x32, 0x35, 0x6a, 0x6e, 0xe9, 0xde, 0x15, 0x58, 0x37, 0x07, 0x80, 0x2b,
	0xd2, 0x7b, 0xee, 0x25, 0x83, 0x48, 0xd5, 0xa8, 0x94, 0xc3, 0x53, 0x2d, 0x86, 0xa7, 0x1a, 0x92,
	0x21, 0xb7, 0xc0, 0x6c, 0x54, 0xbc, 0x3b, 0xcf, 0x26, 0x48, 0x07, 0x05, 0xb4, 0xa0, 0x11, 0x97,
	0x3b, 0x55, 0x9e, 0x8f, 0xd8, 0x90, 0x03, 0x15, 0x52, 0xce, 0x60, 0xa7, 0x2f, 0x12, 0xb8, 0x2e,
	0x5a, 0x3d, 0xc6, 0xac, 0xb5, 0x81, 0x5c, 0x86, 0x9f, 0xe0, 0xa6, 0xce, 0x50, 0x68, 0x2c, 0xee,
	0x46, 0xdf, 0x58, 0x70, 0x09, 0xa4, 0x9a, 0x3d, 0x76, 0x6f, 0xf2, 0xff, 0xfb, 0xa2, 0x55, 0x03,
	0x2a, 0x60, 0xdc, 0xd1, 0x3d, 0xe4, 0xf2, 0x4d, 0xf3, 0x37, 0x3b, 0x05, 0x4d, 0x9c, 0x12, 0xb1,
	0xf6, 0xbd, 0x92, 0x23, 0xbc, 0x0a, 0x09, 0x95, 0x31, 0x98, 0x8b, 0x04, 0xae, 0xde, 0xad, 0xf2,
	0xef, 0x04, 0x18, 0xab, 0x51, 0x13, 0xee, 0x80, 0xff, 0x06, 0xee, 0x93, 0x85, 0xa1, 0x42, 0xa1,
	0x73, 0x9b, 0x5f, 0xb9, 0x88, 0xd1, 0x55, 0xfb, 0x41, 0x02, 0x99, 0xc8, 0x63, 0x1d, 0x59, 0x22,
	0x8a, 0x99, 0xbf, 0x75, 0x59, 0x66, 0xf7, 0x3a, 0x59, 0x3d, 0xf8, 0xf6, 0xeb, 0x5d, 0x7c, 0xb9,
	0x22, 0x15, 0xe5, 0x45, 0x75, 0xc4, 0x7d, 0xda, 0x31, 0x8f, 0xc2, 0x43, 0x09, 0x4c, 0x0f, 0x9f,
	0x9d, 0xa5, 0xa8, 0xae, 0x43, 0xb4, 0xfc, 0xda, 0xa5, 0x68, 0x5d, 0x65, 0xf7, 0xb9, 0xb2, 0x7b,
	0xbe, 0xb2, 0xf2, 0x85, 0xca, 0xd4, 0x17, 0xbd, 0x2d, 0xfb, 0xd2, 0x47, 0xe1, 0x67, 0x09, 0xc0,
	0x88, 0xcd, 0xbd, 0x3c, 0x42, 0x44, 0x88, 0x97, 0x57, 0x2e, 0xc7, 0xeb, 0xaa, 0x7d, 0xc8, 0xd5,
	0x6e, 0xfa, 0x6a, 0x37, 0xfe, 0x5d, 0xad, 0xf6, 0x1c, 0xb3, 0x96, 0xd6, 0x77, 0x80, 0xf2, 0xe3,
	0xaf, 0xfc, 0x37, 0x64, 0x5d, 0x39, 0x3e, 0x2d, 0x48, 0x27, 0xa7, 0x05, 0xe9, 0xe7, 0x69, 0x41,
	0x7a, 0x7b, 0x56, 0x88, 0x9d, 0x9c, 0x15, 0x62, 0xdf, 0xcf, 0x0a, 0xb1, 0x9d, 0x4c, 0xe8, 0x09,
	0x61, 0x9e, 0x83, 0x68, 0x63, 0x82, 0x3f, 0x7d, 0xb7, 0xff, 0x04, 0x00, 0x00, 0xff, 0xff, 0x74,
	0x02, 0x47, 0x79, 0xdf, 0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error)
	// Cria um novo pedido de pagamento para a loja informada.
	CreatePaymentRequest(ctx context.Context, in *MsgCreatePaymentRequest, opts ...grpc.CallOption) (*MsgCreatePaymentRequestResponse, error)
	// Paga um pedido pendente.
	PayPaymentRequest(ctx context.Context, in *MsgPayPaymentRequest, opts ...grpc.CallOption) (*MsgPayPaymentRequestResponse, error)
	// Paga um pedido pendente e transfere um certificado na mesma tx (atômico).
	PayWithCertificate(ctx context.Context, in *MsgPayWithCertificate, opts ...grpc.CallOption) (*MsgPayWithCertificateResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error) {
	out := new(MsgUpdateParamsResponse)
	err := c.cc.Invoke(ctx, "/byx.payments.v1.Msg/UpdateParams", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) CreatePaymentRequest(ctx context.Context, in *MsgCreatePaymentRequest, opts ...grpc.CallOption) (*MsgCreatePaymentRequestResponse, error) {
	out := new(MsgCreatePaymentRequestResponse)
	err := c.cc.Invoke(ctx, "/byx.payments.v1.Msg/CreatePaymentRequest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) PayPaymentRequest(ctx context.Context, in *MsgPayPaymentRequest, opts ...grpc.CallOption) (*MsgPayPaymentRequestResponse, error) {
	out := new(MsgPayPaymentRequestResponse)
	err := c.cc.Invoke(ctx, "/byx.payments.v1.Msg/PayPaymentRequest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) PayWithCertificate(ctx context.Context, in *MsgPayWithCertificate, opts ...grpc.CallOption) (*MsgPayWithCertificateResponse, error) {
	out := new(MsgPayWithCertificateResponse)
	err := c.cc.Invoke(ctx, "/byx.payments.v1.Msg/PayWithCertificate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	UpdateParams(context.Context, *MsgUpdateParams) (*MsgUpdateParamsResponse, error)
	// Cria um novo pedido de pagamento para a loja informada.
	CreatePaymentRequest(context.Context, *MsgCreatePaymentRequest) (*MsgCreatePaymentRequestResponse, error)
	// Paga um pedido pendente.
	PayPaymentRequest(context.Context, *MsgPayPaymentRequest) (*MsgPayPaymentRequestResponse, error)
	// Paga um pedido pendente e transfere um certificado na mesma tx (atômico).
	PayWithCertificate(context.Context, *MsgPayWithCertificate) (*MsgPayWithCertificateResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) UpdateParams(ctx context.Context, req *MsgUpdateParams) (*MsgUpdateParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateParams not implemented")
}
func (*UnimplementedMsgServer) CreatePaymentRequest(ctx context.Context, req *MsgCreatePaymentRequest) (*MsgCreatePaymentRequestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePaymentRequest not implemented")
}
func (*UnimplementedMsgServer) PayPaymentRequest(ctx context.Context, req *MsgPayPaymentRequest) (*MsgPayPaymentRequestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PayPaymentRequest not implemented")
}
func (*UnimplementedMsgServer) PayWithCertificate(ctx context.Context, req *MsgPayWithCertificate) (*MsgPayWithCertificateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PayWithCertificate not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_UpdateParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateParams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/byx.payments.v1.Msg/UpdateParams",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateParams(ctx, req.(*MsgUpdateParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_CreatePaymentRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCreatePaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CreatePaymentRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/byx.payments.v1.Msg/CreatePaymentRequest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CreatePaymentRequest(ctx, req.(*MsgCreatePaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_PayPaymentRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgPayPaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).PayPaymentRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/byx.payments.v1.Msg/PayPaymentRequest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).PayPaymentRequest(ctx, req.(*MsgPayPaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_PayWithCertificate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgPayWithCertificate)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).PayWithCertificate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/byx.payments.v1.Msg/PayWithCertificate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).PayWithCertificate(ctx, req.(*MsgPayWithCertificate))
	}
	return interceptor(ctx, in, info, handler)
}

var Msg_serviceDesc = _Msg_serviceDesc
var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "byx.payments.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateParams",
			Handler:    _Msg_UpdateParams_Handler,
		},
		{
			MethodName: "CreatePaymentRequest",
			Handler:    _Msg_CreatePaymentRequest_Handler,
		},
		{
			MethodName: "PayPaymentRequest",
			Handler:    _Msg_PayPaymentRequest_Handler,
		},
		{
			MethodName: "PayWithCertificate",
			Handler:    _Msg_PayWithCertificate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "byx/payments/v1/tx.proto",
}

func (m *MsgUpdateParams) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateParams) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateParams) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdateParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgCreatePaymentRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreatePaymentRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreatePaymentRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ExpiresInSeconds != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.ExpiresInSeconds))
		i--
		dAtA[i] = 0x28
	}
	if len(m.Memo) > 0 {
		i -= len(m.Memo)
		copy(dAtA[i:], m.Memo)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Memo)))
		i--
		dAtA[i] = 0x22
	}
	if m.AmountMicrobyx != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.AmountMicrobyx))
		i--
		dAtA[i] = 0x18
	}
	if m.LojaId != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.LojaId))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgCreatePaymentRequestResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreatePaymentRequestResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreatePaymentRequestResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *MsgPayPaymentRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgPayPaymentRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgPayPaymentRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.RequestId != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.RequestId))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgPayPaymentRequestResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgPayPaymentRequestResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgPayPaymentRequestResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.PaymentRequest != nil {
		{
			size, err := m.PaymentRequest.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTx(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgPayWithCertificate) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgPayWithCertificate) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgPayWithCertificate) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Payer) > 0 {
		i -= len(m.Payer)
		copy(dAtA[i:], m.Payer)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Payer)))
		i--
		dAtA[i] = 0x1a
	}
	if m.CertificateId != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.CertificateId))
		i--
		dAtA[i] = 0x10
	}
	if len(m.RequestId) > 0 {
		i -= len(m.RequestId)
		copy(dAtA[i:], m.RequestId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.RequestId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgPayWithCertificateResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgPayWithCertificateResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgPayWithCertificateResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.PaymentRequest != nil {
		{
			size, err := m.PaymentRequest.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTx(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgUpdateParams) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = m.Params.Size()
	n += 1 + l + sovTx(uint64(l))
	return n
}

func (m *MsgUpdateParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgCreatePaymentRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.LojaId != 0 {
		n += 1 + sovTx(uint64(m.LojaId))
	}
	if m.AmountMicrobyx != 0 {
		n += 1 + sovTx(uint64(m.AmountMicrobyx))
	}
	l = len(m.Memo)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.ExpiresInSeconds != 0 {
		n += 1 + sovTx(uint64(m.ExpiresInSeconds))
	}
	return n
}

func (m *MsgCreatePaymentRequestResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovTx(uint64(m.Id))
	}
	return n
}

func (m *MsgPayPaymentRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.RequestId != 0 {
		n += 1 + sovTx(uint64(m.RequestId))
	}
	return n
}

func (m *MsgPayPaymentRequestResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.PaymentRequest != nil {
		l = m.PaymentRequest.Size()
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgPayWithCertificate) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.RequestId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.CertificateId != 0 {
		n += 1 + sovTx(uint64(m.CertificateId))
	}
	l = len(m.Payer)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgPayWithCertificateResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.PaymentRequest != nil {
		l = m.PaymentRequest.Size()
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgUpdateParams) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateParams: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateParams: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCreatePaymentRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreatePaymentRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreatePaymentRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LojaId", wireType)
			}
			m.LojaId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LojaId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AmountMicrobyx", wireType)
			}
			m.AmountMicrobyx = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AmountMicrobyx |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Memo", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Memo = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExpiresInSeconds", wireType)
			}
			m.ExpiresInSeconds = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ExpiresInSeconds |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCreatePaymentRequestResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreatePaymentRequestResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreatePaymentRequestResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgPayPaymentRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgPayPaymentRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgPayPaymentRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RequestId", wireType)
			}
			m.RequestId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RequestId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgPayPaymentRequestResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgPayPaymentRequestResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgPayPaymentRequestResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PaymentRequest", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.PaymentRequest == nil {
				m.PaymentRequest = &PaymentRequest{}
			}
			if err := m.PaymentRequest.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgPayWithCertificate) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgPayWithCertificate: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgPayWithCertificate: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RequestId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RequestId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CertificateId", wireType)
			}
			m.CertificateId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CertificateId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Payer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Payer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgPayWithCertificateResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgPayWithCertificateResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgPayWithCertificateResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PaymentRequest", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.PaymentRequest == nil {
				m.PaymentRequest = &PaymentRequest{}
			}
			if err := m.PaymentRequest.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
